services:
  petio:
    image: ghcr.io/petio-team/petio@sha256:1c5a9276a844f4284601cbe332905864950545ebdeaad74bacb9097ea4f4b333
    restart: unless-stopped
    ports:
      - 7777:7777
    volumes:
      - ./config:/app/api/config
      - ./logs:/app/logs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
  mongo:
    image: mongo:4.4.22
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
