services:
  motioneye:
    image: ccrisan/motioneye:master-amd64
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8765:8765
    volumes:
      - ${VOL_1}:/etc/motioneye
      - ${VOL_2}:/var/lib/motioneye
