services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3@sha256:42a200db07b4e70fbf32c594ad4521cf16399b8e54bbb5adceae98e7566dfbeb
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=[YOUR-app-IP]
      - PMA_PORT=3306
      - PMA_USER=app
      - PMA_PASSWORD=${PMA_PASSWORD}
