services:
  watchyourlan:
    image: aceberg/watchyourlan:2.1.4@sha256:f77532ca7c3c9a4398cb094df7674013a3d7fcf4699386f1e456c24df6fef00e
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data/WatchYourLAN
    environment:
      - IFACES="eth0"
      - TZ="UTC"
