services:
  onedev:
    image: 1dev/server:16.6.1
    restart: unless-stopped
    ports:
      - 6610:6610
      - 6611:6611
    volumes:
      - ${VOL_1}:/opt/onedev
      - ${VOL_2}:/var/run/docker.sock
    environment:
      - hibernate_dialect=io.onedev.server.persistence.PostgreSQLDialect
      - hibernate_connection_driver_class=org.postgresql.Driver
      - hibernate_connection_url=jdbc:postgresql://onedev-db:5432/onedev
      - hibernate_connection_username=app
      - hibernate_connection_password=${hibernate_connection_password}
      - initial_user=app
      - initial_password=${initial_password}
      - initial_email=admin@example.com
      - initial_server_url=http://localhost:6610
  onedev-db:
    image: postgres:14@sha256:9e279cc7fc6e908da071befe389c576bd6752dbd295a9c078f96a75bab03e54c
    restart: unless-stopped
    volumes:
      - ${VOL_3}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=${hibernate_connection_password}
      - POSTGRES_DB=onedev
