services:
  app:
    image: portainer/agent:2.45.0
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9001:9001
    volumes:
      - ${VOL_1}:/var/run/docker.sock
      - ${VOL_2}:/var/lib/docker/volumes
