id: portainer-agent
name: Portainer Agent
author: Community
category: Productivity
description: Portainer uses the Portainer Agent container to communicate with the Portainer Server instance and provide access to the node's resources. This document will outline how to install the Portainer Agent on your node and how to connect to it from your Portainer Server instance. If you do not have a working Portainer Server instance yet, please refer to the Portainer Server installation guide first.
ugos:
  app_id: com.upkforge.docker.portaineragent
  version: 0.1.0
  port: 9001
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Var run docker.sock folder
  help: Folder on the NAS for Portainer Agent's var run docker.sock. It is mounted into the container at /var/run/docker.sock; Portainer Agent has full read and write access to it.
  type: path
- key: VOL_2
  label: Var lib docker volumes folder
  help: Folder on the NAS for Portainer Agent's var lib docker volumes. It is mounted into the container at /var/lib/docker/volumes; Portainer Agent has full read and write access to it.
  type: path
volumes:
- container_path: /var/run/docker.sock
  label: Var run docker.sock
  default_host_subpath: app-var-run-docker-sock
- container_path: /var/lib/docker/volumes
  label: Var lib docker volumes
  default_host_subpath: app-var-lib-docker-volumes
