id: immich-without-machine-learning
name: Immich without machine learning
author: Community
category: AI
description: Self-hosted photo and video storage. This does not include the machine learning part.
ugos:
  app_id: com.upkforge.docker.immichwithoutmachinelearning
  version: 0.1.0
  port: 2283
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Usr src app upload folder
  help: Folder on the NAS for Immich without machine learning's usr src app upload. It is mounted into the container at /usr/src/app/upload; Immich without machine learning has full read and write access to it.
  type: path
- key: VOL_2
  label: Var lib postgresql data folder
  help: Folder on the NAS for Immich without machine learning's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; Immich without machine learning has full read and write access to it.
  type: path
- key: DB_PASSWORD
  label: DB PASSWORD
  type: password
volumes:
- container_path: /usr/src/app/upload
  label: Usr src app upload
  default_host_subpath: immich-server-usr-src-app-upload
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: database-var-lib-postgresql-data
