services:
  app:
    image: louislam/dockge:1.5.0@sha256:335c6368b880ecc203236ed89e6e5232e0d6578e8ef5920e4a502390451502bf
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - ${VOL_1}:/var/run/docker.sock
      - ${VOL_2}:/app/data
      - ${VOL_3}:/DATA/AppData/app-dockge/stacks
    environment:
      - DOCKGE_STACKS_DIR=/DATA/AppData/app-dockge/stacks
