id: nocodb
name: NocoDB
author: Community
category: Developer
description: NocoDB allows building no-code database solutions with ease of spreadsheets. Bring your own database or choose ours! Millions of rows? Not a problem. Your Data. Your rules. You are in control.
ugos:
  app_id: com.upkforge.docker.nocodb
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Usr src app data folder
  help: Folder on the NAS for NocoDB's usr src app data. It is mounted into the container at /usr/src/app/data; NocoDB has full read and write access to it.
  label_de: Usr src App Daten-Ordner
  help_de: Ordner auf der NAS für NocoDBs Usr src App Daten. Wird im Container unter /usr/src/app/data eingebunden; NocoDB hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib postgresql data folder
  help: Folder on the NAS for NocoDB's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; NocoDB has full read and write access to it.
  label_de: Var lib postgresql Daten-Ordner
  help_de: Ordner auf der NAS für NocoDBs Var lib postgresql Daten. Wird im Container unter /var/lib/postgresql/data eingebunden; NocoDB hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_3
  label: Data folder
  help: Folder on the NAS for NocoDB's data. It is mounted into the container at /data; NocoDB has full read and write access to it.
  label_de: Daten-Ordner
  help_de: Ordner auf der NAS für NocoDBs Daten. Wird im Container unter /data eingebunden; NocoDB hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: NC_AUTH_JWT_SECRET
  label: NC AUTH JWT SECRET
  type: password
- key: POSTGRES_PASSWORD
  label: POSTGRES PASSWORD
  type: password
volumes:
- container_path: /usr/src/app/data
  label: Usr src app data
  default_host_subpath: nocodb-usr-src-app-data
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: nocodb-db-var-lib-postgresql-data
- container_path: /data
  label: Data
  default_host_subpath: nocodb-redis-data
