services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:2.8.7@sha256:eef3ee7810d0e4702afa4a0ff55b10bbbfcaa16c98a277fe1b7f4cb6d5d426b4
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
