services:
  rdtclient:
    image: rogerfar/rdtclient:2.0.142
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 6500:6500
    volumes:
      - ${VOL_1}:/data/downloads
      - ${VOL_2}:/data/db
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
      - UMASK=002
