id: excalidraw
name: Excalidraw
author: excalidraw
category: Productivity
description: >-
  Excalidraw is a virtual hand-drawn style whiteboard platform supporting infinite canvas and end-to-end encrypted collaboration. An intuitive interface offers a hand-drawn experience, ideal for brainstorming, design sketches, or educational scenarios, meeting diverse creative needs.


  Core features include an infinite canvas whiteboard and end-to-end encrypted collaboration. Hand-drawn style with shape library support allows creating rich graphics, enhanced by image insertion capabilities. Dark mode improves user experience, catering to diverse users.


  It provides export options including PNG, SVG, and clipboard for easy content sharing. Drawing capabilities cover rectangle, circle, diamond, arrow, line, free-draw, and eraser, with arrow-binding and labeled arrow support. Undo, redo, zoom, and panning functionalities optimize operations. With creativity and security at the core, the platform delivers a modern whiteboard design solution.


  **Key Features:**

  - Infinite canvas whiteboard supporting hand-drawn style

  - Shape library support for creating rich graphics

  - Image insertion capability

  - Dark mode

  - Export to PNG, SVG, and clipboard

  - Open format - export drawings as an `.excalidraw` json file

  - Wide range of tools - rectangle, circle, diamond, arrow, line, free-draw, eraser...

  - Arrow-binding & labeled arrows

  - Undo and redo

  - Zoom and panning support


  **Learn More:**

  - [Excalidraw Official Website](https://excalidraw.com/)

  - [Excalidraw GitHub](https://github.com/excalidraw/excalidraw)
homepage: https://excalidraw.com/
source_code: https://github.com/excalidraw/excalidraw
ugos:
  app_id: com.upkforge.docker.excalidraw
  version: 0.1.0
  port: 17638
  open_type: tab
  tag_type: utility
