id: viseron
name: Viseron
author: Community
category: AI
description: Viseron is a self-hosted, local only NVR and AI Computer Vision software
ugos:
  app_id: com.upkforge.docker.viseron
  version: 0.1.0
  port: 8888
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Segments folder
  help: Folder on the NAS for Viseron's segments. It is mounted into the container at /segments; Viseron has full read and write access to it.
  type: path
- key: VOL_2
  label: Snapshots folder
  help: Folder on the NAS for Viseron's snapshots. It is mounted into the container at /snapshots; Viseron has full read and write access to it.
  type: path
- key: VOL_3
  label: Thumbnails folder
  help: Folder on the NAS for Viseron's thumbnails. It is mounted into the container at /thumbnails; Viseron has full read and write access to it.
  type: path
- key: VOL_4
  label: Event clips folder
  help: Folder on the NAS for Viseron's event clips. It is mounted into the container at /event_clips; Viseron has full read and write access to it.
  type: path
- key: VOL_5
  label: Config folder
  help: Folder on the NAS for Viseron's config. It is mounted into the container at /config; Viseron has full read and write access to it.
  type: path
volumes:
- container_path: /segments
  label: Segments
  default_host_subpath: viseron-segments
- container_path: /snapshots
  label: Snapshots
  default_host_subpath: viseron-snapshots
- container_path: /thumbnails
  label: Thumbnails
  default_host_subpath: viseron-thumbnails
- container_path: /event_clips
  label: Event clips
  default_host_subpath: viseron-event-clips
- container_path: /config
  label: Config
  default_host_subpath: viseron-config
