id: sftpgo
name: SFTPGO
author: Community
category: Others
description: Full-featured and highly configurable SFTP, HTTP/S, FTP/S and WebDAV server - S3, Google Cloud Storage, Azure Blob
ugos:
  app_id: com.upkforge.docker.sftpgo
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Srv sftpgo folder
  help: Folder on the NAS for SFTPGO's srv sftpgo. It is mounted into the container at /srv/sftpgo; SFTPGO has full read and write access to it.
  label_de: Srv sftpgo-Ordner
  help_de: Ordner auf der NAS für SFTPGOs Srv sftpgo. Wird im Container unter /srv/sftpgo eingebunden; SFTPGO hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib sftpgo folder
  help: Folder on the NAS for SFTPGO's var lib sftpgo. It is mounted into the container at /var/lib/sftpgo; SFTPGO has full read and write access to it.
  label_de: Var lib sftpgo-Ordner
  help_de: Ordner auf der NAS für SFTPGOs Var lib sftpgo. Wird im Container unter /var/lib/sftpgo eingebunden; SFTPGO hat vollen Lese- und Schreibzugriff darauf.
  type: path
volumes:
- container_path: /srv/sftpgo
  label: Srv sftpgo
  default_host_subpath: sftpgo-srv-sftpgo
- container_path: /var/lib/sftpgo
  label: Var lib sftpgo
  default_host_subpath: sftpgo-var-lib-sftpgo
