services:
  gem-digest-bot:
    image: piero24/gemdigest:1.0@sha256:6f49c511af7f2f7a1b9e652e517e6a222760632e7b69801a4997787e40065cc6
    restart: unless-stopped
    ports:
      - 3333:8080
    volumes:
      - ${VOL_1}:/gem_digest_bot/extra_configs
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ADMIN_USER_ID=123;456
