services:
  v2raya:
    image: mzz2017/v2raya:v2.2.7.5
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${VOL_1}:/lib/modules
      - ${VOL_2}:/etc/resolv.conf
      - ${VOL_3}:/etc/v2raya
