services:
  lobe-chat:
    image: lobehub/lobe-chat:1.143.3@sha256:b2d2454525523d9f0a19c79661f83ec45f13363dbadd5c1180887e77af35d872
    restart: unless-stopped
    ports:
      - 3210:3210
    environment:
      - OPENAI_API_KEY=""
      - OPENAI_PROXY_URL=""
      - CUSTOM_MODELS=""
      - ACCESS_CODE=""
