services:
  jellyfin:
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ${VOL_1}:/media:ro
      - ${VOL_2}:/config/plugins
    image: docker.io/jellyfin/jellyfin:12.0
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      TZ: ${TZ}