services:
  jlesage-handbrake:
    image: jlesage/handbrake:v26.08.2
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/storage
      - ${VOL_3}:/watch
      - ${VOL_4}:/output
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}
