services:
  vocechat:
    image: privoce/vocechat-server:v0.5.36
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 3009:3000
    volumes:
      - ${VOL_1}:/home/vocechat-server/data
    environment:
      - TZ=$TZ
