id: cloudbeaver
name: CloudBeaver
author: joaobosconff
category: Developer
description: CloudBeaver is a web-based database GUI tool which provides rich web interface. You can use it to manage PostgreSQL, MySQL, MariaDB, SQL Server, Oracle, DB2, Firebird, H2, Trino.
homepage: https://dbeaver.com/download/cloudbeaver/
source_code: https://github.com/dbeaver/cloudbeaver
ugos:
  app_id: com.upkforge.docker.cloudbeaver
  version: 0.1.0
  port: 8978
  open_type: tab
  tag_type: devtool
volumes:
- container_path: /opt/cloudbeaver/workspace
  label: Opt cloudbeaver workspace
  user_chosen: false
  default_host_subpath: workspace
