id: openclaw
name: OpenClaw
author: openclaw
category: AI
description: "OpenClaw is an open-source personal AI assistant designed to extend the capabilities of large language models (LLMs) into intelligent agents that actively execute tasks, interact across multiple platforms, and operate continuously. It supports 24/7 operation on the user's own device or server and provides intelligent automation services through common communication tools. OpenClaw connects AI to existing chat channels (such as WhatsApp, Telegram, Discord, etc.) via a locally running \"gateway + agent\" architecture, enabling it not only to answer questions but also to proactively perform actions, manage schedules, process emails, automate workflows, and more. **Key Features**: - Multi-channel Communication Integration: Interact directly with AI through common communication platforms like WhatsApp, Telegram, Slack, Discord, Signal, iMessage, Microsoft Teams, etc., without the need for additional applications. - Continuous Online & Long-term Memory: OpenClaw can run 24/7, possessing persistent memory and context retention capabilities, allowing it to remember preferences, historical conversations, and provide personalized services. - Real Action Execution: Beyond text replies, it can perform system tasks (e.g., clear inbox, send emails, fill forms, schedule appointments, browse web, control browser, etc.). - Skill Expansion & Automated Workflows: Supports community plugins, extended skills, and custom automation scripts, enabling the AI to execute complex tasks in various scenarios. **Learn More:** - [Official Website](https://openclaw.ai) - [Official Documentation](https://docs.openclaw.ai/) - [OpenClaw GitHub Repository](https://github.com/openclaw/openclaw) - [Configure Guide](https://www..com/docs//How-to-Deploy-OpenClaw)"
homepage: https://openclaw.ai
source_code: https://github.com/openclaw/openclaw
warnings:
- service is privileged
ugos:
  app_id: com.upkforge.docker.openclaw
  version: 0.1.0
  port: 24190
  open_type: tab
  tag_type: utility
parameters:
- key: OPENCLAW_GATEWAY_TOKEN
  label: OPENCLAW GATEWAY TOKEN
  type: password
volumes:
- container_path: /home/node/.openclaw
  label: Home node .openclaw
  user_chosen: false
  default_host_subpath: openclaw-home-node-openclaw
