services:
  firefly:
    image: uusec/firefly:4.4
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${VOL_1}:/lib/modules
      - ${VOL_2}:/firefly/conf
    environment:
      - FIREFLY_PASSWORD=${FIREFLY_PASSWORD}
