services:
  firefly:
    image: uusec/firefly:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./firefly-lib-modules:/lib/modules
      - ./conf:/firefly/conf
    environment:
      - FIREFLY_PASSWORD=firefly
