services:
  brave:
    image: kasmweb/brave:1.15.0-rolling@sha256:679eefbde9b44b6de2a73a5b266790393cea11e5756a8ab884798944cfef6ea7
    restart: unless-stopped
    ports:
      - 6901:6901
    volumes:
      - ${VOL_1}:/home/kasm-user/Downloads
    environment:
      - VNC_PW=app
      - LAUNCH_URL=https://community.app.com/
