id: nightscout
name: nightscout
author: Community
category: Home
description: This acts as a web-based CGM (Continuous Glucose Monitor) to allow multiple caregivers to remotely view a patient's glucose data in real time. The server reads a MongoDB which is intended to be data from a physical CGM, where it sends new SGV (sensor glucose values) as the data becomes available. The data is then displayed graphically and blood glucose values are predicted 0.5 hours ahead using an autoregressive second order model. Alarms are generated for high and low values, which can be cleared by any watcher of the data.
ugos:
  app_id: com.upkforge.docker.nightscout
  version: 0.1.0
  port: 1337
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Data db folder
  help: Folder on the NAS for nightscout's data db. It is mounted into the container at /data/db; nightscout has full read and write access to it.
  type: path
- key: API_SECRET
  label: API SECRET
  type: password
volumes:
- container_path: /data/db
  label: Data db
  default_host_subpath: nightscout-mongo-data-db
