services:
  app:
    image: appsmith/appsmith-ce:v1.98.1@sha256:9a5119fdbf22c5ae25c2240a5d5f944b9c44c4fe4a6cfa65934dc3792d24c871
    restart: unless-stopped
    ports:
      - 1080:80
      - 10443:443
    volumes:
      - ./stacks:/appsmith-stacks
