services:
  snapdrop:
    image: linuxserver/snapdrop:version-eac78009
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 10443:443
      - 89:80
    volumes:
      - ${VOL_1}:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
