id: focalboard
name: Focalboard
author: Community
category: Productivity
description: Focalboard is an open source, multilingual, self-hosted project management tool that's an alternative to Trello, Notion, and Asana.
ugos:
  app_id: com.upkforge.docker.focalboard
  version: 0.1.0
  port: 8000
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Opt focalboard data folder
  help: Folder on the NAS for Focalboard's opt focalboard data. It is mounted into the container at /opt/focalboard/data; Focalboard has full read and write access to it.
  type: path
volumes:
- container_path: /opt/focalboard/data
  label: Opt focalboard data
  default_host_subpath: app-opt-focalboard-data
