services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.38.5
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - TZ=${TZ}
      - GENERIC_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
