id: openhab
name: OpenHAB
author: Team
category: Home
description: The open Home Automation Bus (openHAB, pronounced ˈəʊpənˈhæb) is an open source, technology agnostic home automation platform which runs as the center of your smart home! Its ability to integrate a multitude of other devices and systems. openHAB includes other home automation systems, (smart) devices and other technologies into a single solution. To provide a uniform user interface and a common approach to automation rules across the entire system, regardless of the number of manufacturers and sub-systems involved. Giving you the most flexible tool available to make almost any home automation wish come true; if you can think it, odds are that you can implement it with openHAB.
homepage: https://www.openhab.org
source_code: https://github.com/openhab/openhab-distro
warnings:
- service uses host networking
ugos:
  app_id: com.upkforge.docker.openhab
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Openhab addons folder
  help: Folder on the NAS for OpenHAB's openhab addons. It is mounted into the container at /openhab/addons; OpenHAB has full read and write access to it.
  label_de: Openhab addons-Ordner
  help_de: Ordner auf der NAS für OpenHABs Openhab addons. Wird im Container unter /openhab/addons eingebunden; OpenHAB hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Openhab conf folder
  help: Folder on the NAS for OpenHAB's openhab conf. It is mounted into the container at /openhab/conf; OpenHAB has full read and write access to it.
  label_de: Openhab conf-Ordner
  help_de: Ordner auf der NAS für OpenHABs Openhab conf. Wird im Container unter /openhab/conf eingebunden; OpenHAB hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_3
  label: Openhab userdata folder
  help: Folder on the NAS for OpenHAB's openhab userdata. It is mounted into the container at /openhab/userdata; OpenHAB has full read and write access to it.
  label_de: Openhab userdata-Ordner
  help_de: Ordner auf der NAS für OpenHABs Openhab userdata. Wird im Container unter /openhab/userdata eingebunden; OpenHAB hat vollen Lese- und Schreibzugriff darauf.
  type: path
volumes:
- container_path: /openhab/addons
  label: Openhab addons
  default_host_subpath: openhab-openhab-addons
- container_path: /openhab/conf
  label: Openhab conf
  default_host_subpath: openhab-openhab-conf
- container_path: /openhab/userdata
  label: Openhab userdata
  default_host_subpath: openhab-openhab-userdata
