id: ntfy
name: Ntfy.sh
author: Community
category: Developer
description: ntfy (pronounced notify) is a simple HTTP-based pub-sub notification service. It allows you to send notifications to your phone or desktop via scripts from any computer, and/or using a REST API. It's infinitely flexible, and 100% free software.
ugos:
  app_id: com.upkforge.docker.ntfy
  version: 0.1.0
  port: 7200
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Var cache ntfy folder
  help: Folder on the NAS for Ntfy.sh's var cache ntfy. It is mounted into the container at /var/cache/ntfy; Ntfy.sh has full read and write access to it.
  label_de: Var Cache ntfy-Ordner
  help_de: Ordner auf der NAS für Ntfy.shs Var Cache ntfy. Wird im Container unter /var/cache/ntfy eingebunden; Ntfy.sh hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Etc ntfy folder
  help: Folder on the NAS for Ntfy.sh's etc ntfy. It is mounted into the container at /etc/ntfy; Ntfy.sh has full read and write access to it.
  label_de: Etc ntfy-Ordner
  help_de: Ordner auf der NAS für Ntfy.shs Etc ntfy. Wird im Container unter /etc/ntfy eingebunden; Ntfy.sh hat vollen Lese- und Schreibzugriff darauf.
  type: path
volumes:
- container_path: /var/cache/ntfy
  label: Var cache ntfy
  default_host_subpath: app-var-cache-ntfy
- container_path: /etc/ntfy
  label: Etc ntfy
  default_host_subpath: app-etc-ntfy
