id: guacamole
name: Guacamole
author: Community
category: Others
description: Apache Guacamole is a free and open-source, cross-platform, clientless remote desktop gateway maintained by the Apache Software Foundation.
ugos:
  app_id: com.upkforge.docker.guacamole
  version: 0.1.0
  port: 8090
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Var lib mysql folder
  help: Folder on the NAS for Guacamole's var lib mysql. It is mounted into the container at /var/lib/mysql; Guacamole has full read and write access to it.
  type: path
- key: MYSQL_PASSWORD
  label: MYSQL PASSWORD
  type: password
- key: MYSQL_ROOT_PASSWORD
  label: MYSQL ROOT PASSWORD
  type: password
volumes:
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: mysql-var-lib-mysql
