services:
  morphos:
    image: ghcr.io/danvergara/morphos-server:0.6.0@sha256:3d6f64ef386cbb6a7c5d55526e1a69da2d3661a1996d757897e92bf4369088f5
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /DATA/AppData/morphos/tmp:/tmp
