services:
  umbrel:
    image: dockurr/umbrel:1.7.4@sha256:ae33fe21603853c4b8f90afb23493c98f550bfc601274bb74d1a4cadb0dade2e
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data:/data
      - ./umbrel-var-run-docker-sock:/var/run/docker.sock
