services:
  wishlist:
    image: ghcr.io/cmintey/wishlist:v0.66.0
    restart: unless-stopped
    ports:
      - 3280:3280
    volumes:
      - ${VOL_1}:/usr/src/app/uploads
      - ${VOL_2}:/usr/src/app/data
    environment:
      - ORIGIN=
      - TOKEN_TIME=72
      - DEFAULT_CURRENCY=USD
      - LOG_LEVEL=info
