services:
  tugtainer:
    image: quenary/tugtainer:1.40.0
    restart: unless-stopped
    ports:
      - 9412:80
    volumes:
      - ${VOL_1}:/tugtainer
      - ${VOL_2}:/var/run/docker.sock
    environment:
      - TZ=UTC
      - LOG_LEVEL=warning
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ACCESS_TOKEN_LIFETIME_MIN=5
      - REFRESH_TOKEN_LIFETIME_MIN=43200
      - HTTPS=FALSE
