id: tugtainer
name: Tugtainer
author: Community
category: Developer
description: Tugtainer is a self-hosted app for automating updates of your docker containers with a web UI. It's like watchtower but with more control and a user-friendly interface.
ugos:
  app_id: com.upkforge.docker.tugtainer
  version: 0.1.0
  port: 9412
  open_type: tab
  tag_type: devtool
parameters:
- key: JWT_SECRET_KEY
  label: JWT SECRET KEY
  type: password
volumes:
- container_path: /tugtainer
  label: Tugtainer
  user_chosen: false
  default_host_subpath: data
- container_path: /var/run/docker.sock
  label: Var run docker.sock
  user_chosen: false
  default_host_subpath: tugtainer-var-run-docker-sock
