id: warracker
name: Warracker
author: Community
category: Others
description: A self-hosted warranty tracker
warnings:
- service is privileged
ugos:
  app_id: com.upkforge.docker.warracker
  version: 0.1.0
  port: 8005
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Data uploads folder
  help: Folder on the NAS for Warracker's data uploads. It is mounted into the container at /data/uploads; Warracker has full read and write access to it.
  label_de: Daten Uploads-Ordner
  help_de: Ordner auf der NAS für Warrackers Daten Uploads. Wird im Container unter /data/uploads eingebunden; Warracker hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib postgresql data folder
  help: Folder on the NAS for Warracker's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; Warracker has full read and write access to it.
  label_de: Var lib postgresql Daten-Ordner
  help_de: Ordner auf der NAS für Warrackers Var lib postgresql Daten. Wird im Container unter /var/lib/postgresql/data eingebunden; Warracker hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: DB_PASSWORD
  label: DB PASSWORD
  type: password
- key: SMTP_PASSWORD
  label: SMTP PASSWORD
  type: password
volumes:
- container_path: /data/uploads
  label: Data uploads
  default_host_subpath: warracker-data-uploads
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: warrackerdb-var-lib-postgresql-data
