services:
  app:
    image: onlyoffice/documentserver:9.4.0.1
    restart: unless-stopped
    ports:
      - 7400:80
    volumes:
      - ${VOL_1}:/var/log/onlyoffice
      - ${VOL_2}:/var/www/onlyoffice/Data
      - ${VOL_3}:/var/lib/onlyoffice
      - ${VOL_4}:/var/lib/rabbitmq
      - ${VOL_5}:/var/lib/redis
      - ${VOL_6}:/var/lib/postgresql
