id: onlyoffice
name: OnlyOffice
author: Community
category: Productivity
description: Feature-rich web-based office suite with a vast range of collaborative capabilities
ugos:
  app_id: com.upkforge.docker.onlyoffice
  version: 0.1.0
  port: 7400
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Var log onlyoffice folder
  help: Folder on the NAS for OnlyOffice's var log onlyoffice. It is mounted into the container at /var/log/onlyoffice; OnlyOffice has full read and write access to it.
  type: path
- key: VOL_2
  label: Var www onlyoffice Data folder
  help: Folder on the NAS for OnlyOffice's var www onlyoffice data. It is mounted into the container at /var/www/onlyoffice/Data; OnlyOffice has full read and write access to it.
  type: path
- key: VOL_3
  label: Var lib onlyoffice folder
  help: Folder on the NAS for OnlyOffice's var lib onlyoffice. It is mounted into the container at /var/lib/onlyoffice; OnlyOffice has full read and write access to it.
  type: path
- key: VOL_4
  label: Var lib rabbitmq folder
  help: Folder on the NAS for OnlyOffice's var lib rabbitmq. It is mounted into the container at /var/lib/rabbitmq; OnlyOffice has full read and write access to it.
  type: path
- key: VOL_5
  label: Var lib redis folder
  help: Folder on the NAS for OnlyOffice's var lib redis. It is mounted into the container at /var/lib/redis; OnlyOffice has full read and write access to it.
  type: path
- key: VOL_6
  label: Var lib postgresql folder
  help: Folder on the NAS for OnlyOffice's var lib postgresql. It is mounted into the container at /var/lib/postgresql; OnlyOffice has full read and write access to it.
  type: path
volumes:
- container_path: /var/log/onlyoffice
  label: Var log onlyoffice
  default_host_subpath: app-var-log-onlyoffice
- container_path: /var/www/onlyoffice/Data
  label: Var www onlyoffice Data
  default_host_subpath: app-var-www-onlyoffice-data
- container_path: /var/lib/onlyoffice
  label: Var lib onlyoffice
  default_host_subpath: app-var-lib-onlyoffice
- container_path: /var/lib/rabbitmq
  label: Var lib rabbitmq
  default_host_subpath: app-var-lib-rabbitmq
- container_path: /var/lib/redis
  label: Var lib redis
  default_host_subpath: app-var-lib-redis
- container_path: /var/lib/postgresql
  label: Var lib postgresql
  default_host_subpath: app-var-lib-postgresql
