id: authentik
name: Authentik
author: Community
category: Others
description: Authentik is a self-hosted identity and access management platform that provides a secure and scalable solution for managing user accounts, authentication, and authorization. It offers a range of features, including user management, role-based access control, and multi-factor authentication. Authentik is designed to be easy to use and integrate with your existing systems, making it a great choice for organizations looking to improve their security and compliance.
ugos:
  app_id: com.upkforge.docker.authentik
  version: 0.1.0
  port: 19443
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Media folder
  help: Folder on the NAS for Authentik's media. It is mounted into the container at /media; Authentik has full read and write access to it.
  type: path
- key: VOL_2
  label: Templates folder
  help: Folder on the NAS for Authentik's templates. It is mounted into the container at /templates; Authentik has full read and write access to it.
  type: path
- key: VOL_3
  label: Var run docker.sock folder
  help: Folder on the NAS for Authentik's var run docker.sock. It is mounted into the container at /var/run/docker.sock; Authentik has full read and write access to it.
  type: path
- key: VOL_4
  label: Media folder
  help: Folder on the NAS for Authentik's media. It is mounted into the container at /media; Authentik has full read and write access to it.
  type: path
- key: VOL_5
  label: Certs folder
  help: Folder on the NAS for Authentik's certs. It is mounted into the container at /certs; Authentik has full read and write access to it.
  type: path
- key: VOL_6
  label: Templates folder
  help: Folder on the NAS for Authentik's templates. It is mounted into the container at /templates; Authentik has full read and write access to it.
  type: path
- key: VOL_7
  label: Var lib postgresql data folder
  help: Folder on the NAS for Authentik's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; Authentik has full read and write access to it.
  type: path
- key: VOL_8
  label: Data folder
  help: Folder on the NAS for Authentik's data. It is mounted into the container at /data; Authentik has full read and write access to it.
  type: path
- key: AUTHENTIK_POSTGRESQL__PASSWORD
  label: AUTHENTIK POSTGRESQL PASSWORD
  type: password
- key: AUTHENTIK_SECRET_KEY
  label: AUTHENTIK SECRET KEY
  type: password
volumes:
- container_path: /media
  label: Media
  default_host_subpath: authentik-media
- container_path: /templates
  label: Templates
  default_host_subpath: authentik-templates
- container_path: /var/run/docker.sock
  label: Var run docker.sock
  default_host_subpath: authentik-worker-var-run-docker-sock
- container_path: /media
  label: Media
  default_host_subpath: authentik-worker-media
- container_path: /certs
  label: Certs
  default_host_subpath: authentik-worker-certs
- container_path: /templates
  label: Templates
  default_host_subpath: authentik-worker-templates
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: authentik-db-var-lib-postgresql-data
- container_path: /data
  label: Data
  default_host_subpath: authentik-redis-data
