services:
  app:
    image: pawelmalak/flame:multiarch2.3.1@sha256:9f88b17692a0e7393bfceec774dd556a8331032bfb737d7db282a2eedc6b74d1
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - ./data:/app/data
      - ./app-var-run-docker-sock:/var/run/docker.sock
    environment:
      - PASSWORD=${PASSWORD}
