services:
  pwpush:
    image: pglombardo/pwpush:2.11.6
    restart: unless-stopped
    ports:
      - 5100:5100
    volumes:
      - ${VOL_1}:/opt/PasswordPusher/storage
    environment:
      - DATABASE_URL=mysql2://pwpusher:6280144a-56af-486f-9088-ac7301399328@pwpush-db:3306/passwordpusher_db
      - PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT=1
      - PWP__PW__EXPIRE_AFTER_VIEWS_MIN=1
      - PWP__PW__RETRIEVAL_STEP_DEFAULT=true
  pwpush-db:
    image: mariadb:12.3.3
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ${VOL_2}:/var/lib/mysql
    environment:
      - MARIADB_USER=pwpusher
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=passwordpusher_db
      - MARIADB_RANDOM_ROOT_PASSWORD=${MARIADB_RANDOM_ROOT_PASSWORD}
