services:
  pwpush:
    image: pglombardo/pwpush:1.69.3@sha256:7bf7f919b87d818a9cafa2a5c53e2565a577a7b90983b3cd55de90d6de71cf07
    restart: unless-stopped
    ports:
      - 5100:5100
    volumes:
      - ./storage:/opt/PasswordPusher/storage
    environment:
      - DATABASE_URL=mysql2://pwpusher:6280144a-56af-486f-9088-ac7301399328@pwpush-db:3306/passwordpusher_db
      - PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT=1
      - PWP__PW__EXPIRE_AFTER_VIEWS_MIN=1
      - PWP__PW__RETRIEVAL_STEP_DEFAULT=true
  pwpush-db:
    image: mariadb:10.6.5@sha256:ca31f38b6e325ece985d857db7eba1fe59928b4fd83ff8a55cb912c9684b9e43
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_USER=pwpusher
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=passwordpusher_db
      - MARIADB_RANDOM_ROOT_PASSWORD=${MARIADB_RANDOM_ROOT_PASSWORD}
