id: pwpush
name: Password Pusher (Legacy)
author: Community
category: Others
description: Password Pusher is an open source application to communicate passwords over the web. Links to passwords expire after a certain number of views and/or time has passed.
ugos:
  app_id: com.upkforge.docker.pwpush
  version: 0.1.0
  port: 5100
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Opt PasswordPusher storage folder
  help: Folder on the NAS for Password Pusher (Legacy)'s opt passwordpusher storage. It is mounted into the container at /opt/PasswordPusher/storage; Password Pusher (Legacy) has full read and write access to it.
  label_de: Opt PasswordPusher Speicher-Ordner
  help_de: Ordner auf der NAS für Password Pusher (Legacy)s Opt PasswordPusher Speicher. Wird im Container unter /opt/PasswordPusher/storage eingebunden; Password Pusher (Legacy) hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib mysql folder
  help: Folder on the NAS for Password Pusher (Legacy)'s var lib mysql. It is mounted into the container at /var/lib/mysql; Password Pusher (Legacy) has full read and write access to it.
  label_de: Var lib mysql-Ordner
  help_de: Ordner auf der NAS für Password Pusher (Legacy)s Var lib mysql. Wird im Container unter /var/lib/mysql eingebunden; Password Pusher (Legacy) hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: MARIADB_PASSWORD
  label: MARIADB PASSWORD
  type: password
- key: MARIADB_RANDOM_ROOT_PASSWORD
  label: MARIADB RANDOM ROOT PASSWORD
  type: password
volumes:
- container_path: /opt/PasswordPusher/storage
  label: Opt PasswordPusher storage
  default_host_subpath: pwpush-opt-passwordpusher-storage
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: pwpush-db-var-lib-mysql
