id: chromium
name: Chromium
version: 26.08.3
author: jlesage
category: Browser
description: This Image contains a browser-accessible version of chromium.
homepage: https://github.com/jlesage/docker-chromium
ugos:
  app_id: com.upkforge.docker.chromium
  version: 0.1.0
  port: 5802
  open_type: tab
  tag_type: utility
volumes:
- container_path: /config
  label: Config
  user_chosen: false
  default_host_subpath: config
- container_path: /usr/share/fonts
  label: Fonts
  user_chosen: false
  default_host_subpath: fonts
