services:
  coolercontrol:
    image: docker.io/coolercontrol/coolercontrold:5.0.0
    ports:
      - "11987:11987"
    volumes:
      - ./config:/etc/coolercontrol
    environment:
      - TZ=${TZ}
      - CC_PORT=11987
      - CC_HOST_IP4=0.0.0.0
      - "CC_HOST_IP6=::"
      - CC_TLS=OFF
      - CC_DBUS=OFF
      - CC_SERVICE_MANAGER=OFF
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    privileged: true
    restart: unless-stopped
