services:
  lidarr:
    image: linuxserver/lidarr:3.1.0
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8686:8686
    volumes:
      - ./config:/config
      - ${VOL_1}:/music
      - ${VOL_2}:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
