services:
  app:
    image: ghcr.io/home-assistant-libs/python-matter-server:8.1.0@sha256:170aa093ce91c76cde4cc390918307590f0f5558fcec93f913af3cb019e6562a
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data/
      - /run/dbus:/run/dbus
