services:
  app:
    image: ghcr.io/codex-team/codex.docs:v2.3.3
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ${VOL_1}:/usr/src/app/uploads
      - ${VOL_2}:/usr/src/app/db
      - ${VOL_3}:/usr/src/app/docs-config.yaml
