services:
  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server
    restart: unless-stopped
    ports:
      - 18080:8080
    volumes:
      - ./models:/models
    environment:
      - LLAMA_ARG_N_GPU_LAYERS=999
      - LLAMA_ARG_CONTEXT_SIZE=8192
