services:
  app:
    image: linuxserver/code-server:4.137.0
    restart: unless-stopped
    ports:
      - 8080:8443
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/projects
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
