services:
  davis:
    image: ghcr.io/tchapi/davis-standalone:5.4.4
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=mysql
      - DATABASE_URL=mysql://app:0c9d2acc-d4f3-423c-8361-86f35cdd3eb2@davis-mysql:3306/davis?serverVersion=10.6.10&charset=utf8mb4
      - MAILER_DSN=smtp://:@davis-mailpit:1025
      - ADMIN_LOGIN=app
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_REALM=
      - AUTH_METHOD=
      - CALDAV_ENABLED=
      - CARDDAV_ENABLED=
      - WEBDAV_ENABLED=
      - WEBDAV_TMP_DIR=
      - WEBDAV_PUBLIC_DIR=
      - WEBDAV_HOMES_DIR=
      - INVITE_FROM_ADDRESS=
      - APP_TIMEZONE=UTC
  davis-mailpit:
    image: axllent/mailpit:v1.31.1
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - ${VOL_1}:/data
    environment:
      - TZ=UTC
  davis-mysql:
    image: mariadb:12.3.3
    restart: unless-stopped
    volumes:
      - ${VOL_2}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=davis
      - MYSQL_USER=app
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
