services:
  webdav:
    image: ugeek/webdav:amd64
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5005:80
    volumes:
      - ${VOL_1}:/media
    environment:
      - GID=1000
      - PASSWORD=${PASSWORD}
      - TZ=Europe/Madrid
      - UDI=1000
      - USERNAME=${PASSWORD}
