services:
  vikunja-v2:
    image: vikunja/vikunja:2.5.0@sha256:22df4c1bc8843c28d383bc5f52b59e7b601bf5f6560b36b29c0a500833c77fa3
    restart: unless-stopped
    ports:
      - 8082:3456
    volumes:
      - ./files:/app/vikunja/files
    environment:
      - VIKUNJA_SERVICE_PUBLICURL=http://<your public frontend url with slash>/
      - VIKUNJA_DATABASE_HOST=vikunja-v2-db
      - VIKUNJA_DATABASE_PASSWORD=${VIKUNJA_DATABASE_PASSWORD}
      - VIKUNJA_DATABASE_TYPE=mysql
      - VIKUNJA_DATABASE_USER=vikunja
      - VIKUNJA_DATABASE_DATABASE=vikunja
  vikunja-v2-db:
    image: mariadb:11@sha256:efb4959ef2c835cd735dbc388eb9ad6aab0c78dd64febcd51bc17481111890c4
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=vikunja
      - MYSQL_PASSWORD=${VIKUNJA_DATABASE_PASSWORD}
      - MYSQL_DATABASE=vikunja
