services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:0.33.2
    restart: unless-stopped
    ports:
      - 14592:3000
    volumes:
      - ./data:/data
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - DATA_DIR=/data
      - NEXTAUTH_URL=http://localhost:14592
      - NEXTAUTH_SECRET=change_this_to_a_long_random_string
      - MEILI_MASTER_KEY=change_this_to_a_long_random_string
      - OPENAI_API_KEY=
  karakeep-chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:release
    restart: unless-stopped
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.41.0
    restart: unless-stopped
    volumes:
      - ./meilisearch:/meili_data
    environment:
      - MEILI_MASTER_KEY=change_this_to_a_long_random_string
      - MEILI_NO_ANALYTICS=true
