services:
  navidrome:
    image: deluan/navidrome:0.63.2
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 4533:4533
    volumes:
      - ${VOL_1}:/data
      - ${VOL_2}:/music
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_BASEURL=
      - TZ=$TZ
