id: jenkins
name: Jenkins CI/CD
author: bepp-boop
category: Developer
description: A server for creating pipelines for Jenkins continuous integration and delivery.
homepage: https://www.jenkins.io/
source_code: https://github.com/jenkinsci/jenkins
ugos:
  app_id: com.upkforge.docker.jenkins
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Data folder
  help: Folder on the NAS for Jenkins CI/CD's data. It is mounted into the container at /data; Jenkins CI/CD has full read and write access to it.
  type: path
- key: VOL_2
  label: Var jenkins home folder
  help: Folder on the NAS for Jenkins CI/CD's var jenkins home. It is mounted into the container at /var/jenkins_home; Jenkins CI/CD has full read and write access to it.
  type: path
volumes:
- container_path: /data
  label: Data
  default_host_subpath: jenkins-data
- container_path: /var/jenkins_home
  label: Var jenkins home
  default_host_subpath: jenkins-var-jenkins-home
