id: mariadb
name: MariaDB
author: WisdomSky
category: Developer
description: >-
  MariaDB Server is one of the most popular open source relational databases. It’s made by the original developers of MySQL and guaranteed to stay open source. It is part of most cloud offerings and the default in most Linux distributions.


  It is built upon the values of performance, stability, and openness, and MariaDB Foundation ensures contributions will be accepted on technical merit. Recent new functionality includes advanced clustering with Galera Cluster 4, compatibility features with Oracle Database and Temporal Data Tables, allowing one to query the data as it stood at any point in the past.
homepage: https://mariadb.org/
source_code: https://github.com/MariaDB/server
ugos:
  app_id: com.upkforge.docker.mariadb
  version: 0.1.0
  port: 3306
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Config folder
  help: Folder on the NAS for MariaDB's config. It is mounted into the container at /config; MariaDB has full read and write access to it.
  type: path
- key: MYSQL_ROOT_PASSWORD
  label: MYSQL ROOT PASSWORD
  type: password
volumes:
- container_path: /config
  label: Config
  default_host_subpath: mariadb-config
