id: melody-hub
name: MelodyHub
version: 1.0.0
author: gefl24
category: Media
homepage: https://github.com/gefl24/melody-hub
ugos:
  app_id: com.upkforge.docker.melodyhub
  version: 0.1.0
  port: 3006
  open_type: tab
  tag_type: media
volumes:
- container_path: /app/data
  label: Data
  user_chosen: false
  default_host_subpath: data
- container_path: /app/music
  label: Music
  user_chosen: false
  default_host_subpath: music
