services:
  poste-io:
    image: analogic/poste.io:2.5.14@sha256:4722c66d70034bb6b0f20be027cdea8659f1ae164ed5ee9aa52b2b703450cabd
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - TZ=UTC
