services:
  faster-whisper:
    image: linuxserver/faster-whisper:3.5.0@sha256:afd508a010d857c7b0e4e09d637f45e6b807e07d8ff77505bb6706c252eac197
    restart: unless-stopped
    ports:
      - 10300:10300
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=tiny-int8
      - WHISPER_BEAM=1
      - WHISPER_LANG=en
