services:
  wg-easy-v15:
    image: ghcr.io/wg-easy/wg-easy:15@sha256:0e7bc9d34e86ddcaa92bc700d4d7dc9b33291dbc07ac8d13382f7c2095f949ec
    restart: unless-stopped
    ports:
      - 51820:51820
      - 51821:51821
    volumes:
      - ./data:/etc/wireguard
    environment:
      - INIT_ENABLED=true
      - INIT_USERNAME=app
      - INIT_PASSWORD=changeme
      - INIT_HOST=[YOUR_PUBLIC_IP]
      - INIT_PORT=51820
      - INIT_DNS=1.1.1.1,8.8.8.8
      - INIT_IPV4_CIDR=10.8.0.0/24
      - INIT_IPV6_CIDR=fd42:42:42::/64
