services:
  nzbfast:
    image: nzbfast/nzbfast:1.4.0
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 6790:6789
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/watch
      - ${VOL_3}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - NZBFAST_APIKEY=
