services:
  budibase:
    image: budibase/budibase:3.41.3@sha256:f05b90c2b8afc951feb99931bb4646d2c94af37d9c576ef3c4e01d4fdc296dc1
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./data:/data
