services:
  gitea-mirror:
    image: ghcr.io/raylabshq/gitea-mirror:v3.36.1
    restart: unless-stopped
    ports:
      - 4321:4321
    volumes:
      - ${VOL_1}:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:data/gitea-mirror.db
      - HOST=0.0.0.0
      - PORT=4321
      - BETTER_AUTH_URL=http://0.0.0.0:4321
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
