services:
  app:
    image: couchdb:3.5.2.1
    restart: unless-stopped
    ports:
      - 5984:5984
    volumes:
      - ${VOL_1}:/opt/couchdb/data
      - ${VOL_2}:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=${COUCHDB_PASSWORD}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
