id: obsidian-livesync
name: Obsidian Livesync
author: Community
category: Developer
description: Self-hosted database for synchronizing Obsidian vaults.
ugos:
  app_id: com.upkforge.docker.obsidianlivesync
  version: 0.1.0
  port: 5984
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Opt couchdb data folder
  help: Folder on the NAS for Obsidian Livesync's opt couchdb data. It is mounted into the container at /opt/couchdb/data; Obsidian Livesync has full read and write access to it.
  type: path
- key: VOL_2
  label: Opt couchdb etc local.ini folder
  help: Folder on the NAS for Obsidian Livesync's opt couchdb etc local.ini. It is mounted into the container at /opt/couchdb/etc/local.ini; Obsidian Livesync has full read and write access to it.
  type: path
- key: COUCHDB_PASSWORD
  label: COUCHDB PASSWORD
  type: password
volumes:
- container_path: /opt/couchdb/data
  label: Opt couchdb data
  default_host_subpath: app-opt-couchdb-data
- container_path: /opt/couchdb/etc/local.ini
  label: Opt couchdb etc local.ini
  default_host_subpath: app-opt-couchdb-etc-local-ini
