services:
  downtify:
    image: ghcr.io/henriquesebastiao/downtify:2.10.2
    restart: unless-stopped
    ports:
      - 8582:8000
    volumes:
      - ${VOL_1}:/downloads
      - ${VOL_2}:/data
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
