services:
  romm:
    image: rommapp/romm:4.8.1
    restart: unless-stopped
    ports:
      - 8285:8080
    volumes:
      - ./resources:/romm/resources
      - ./redis-data:/redis-data
      - ./library:/romm/library
      - ./assets:/romm/assets
      - ./config:/romm/config
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=${DB_PASSWD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - IGDB_CLIENT_ID=${ROMM_AUTH_SECRET_KEY}
      - IGDB_CLIENT_SECRET=${ROMM_AUTH_SECRET_KEY}
      - SCREENSCRAPER_USER=${ROMM_AUTH_SECRET_KEY}
      - SCREENSCRAPER_PASSWORD=${ROMM_AUTH_SECRET_KEY}
      - STEAMGRIDDB_API_KEY=${ROMM_AUTH_SECRET_KEY}
  romm-db:
    image: mariadb:11.8.2
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWD}
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=${DB_PASSWD}
