id: romm
name: RomM
author: rommapp
category: Media
description: >-
  RomM is a self-hosted game collection management app designed for emulator enthusiasts, offering a convenient way to scan, enrich, browse, and play games. Its responsive Web interface allows users to manage collections via any modern browser, supporting over 400 platforms, ideal for retro gaming fans building personal game libraries.


  The app's core features include robust library management and seamless gameplay. It fetches metadata from IGDB, Screenscraper, and MobyGames, and custom artwork from SteamGridDB, enhancing the visual appeal of collections. Users can play games directly in the browser using EmulatorJS and RuffleRS, with support for multi-disk games, DLCs, patches, and manuals. It also enables parsing and filtering by filename tags for tailored organization. Additionally, it supports multi-user accounts with limited access permissions, allowing library sharing with friends and displaying RetroAchievements.


  It can be flexibly deployed on personal servers or NAS devices, with official apps for Playnite and muOS enhancing cross-device access. Users can upload, update, or delete games via the Web interface, with community support documentation expanding functionality. Whether managing a personal retro game library or sharing with others, the app's intuitive interface and high customizability deliver a modern game management platform, meeting diverse needs.


  **Key Features:**

  - Scan and enhance your game library with metadata from IGDB, Screenscraper and MobyGames

  - Fetch custom artwork from SteamGridDB

  - Display your achievements from Retroachievements

  - Metadata available for 400+ platforms

  - Play games directly from the browser using EmulatorJS and RuffleRS

  - Share your library with friends with limited access and permissions

  - Official apps for Playnite and muOS

  - Supports multi-disk games, DLCs, mods, hacks, patches, and manuals

  - Parse and filter by tags in filenames

  - View, upload, update, and delete games from any modern web browser


  **Learn More:**

  - [RomM Official Website](https://romm.app)

  - [RomM GitHub Repository](https://github.com/rommapp/romm)
homepage: https://romm.app
source_code: https://github.com/rommapp/romm
ugos:
  app_id: com.upkforge.docker.romm
  version: 0.1.0
  port: 8285
  open_type: tab
  tag_type: media
parameters:
- key: VOL_1
  label: Romm resources folder
  help: Folder on the NAS for RomM's romm resources. It is mounted into the container at /romm/resources; RomM has full read and write access to it.
  type: path
- key: VOL_2
  label: Redis data folder
  help: Folder on the NAS for RomM's redis data. It is mounted into the container at /redis-data; RomM has full read and write access to it.
  type: path
- key: VOL_3
  label: Romm library folder
  help: Folder on the NAS for RomM's romm library. It is mounted into the container at /romm/library; RomM has full read and write access to it.
  type: path
- key: VOL_4
  label: Romm assets folder
  help: Folder on the NAS for RomM's romm assets. It is mounted into the container at /romm/assets; RomM has full read and write access to it.
  type: path
- key: VOL_5
  label: Romm config folder
  help: Folder on the NAS for RomM's romm config. It is mounted into the container at /romm/config; RomM has full read and write access to it.
  type: path
- key: VOL_6
  label: Var lib mysql folder
  help: Folder on the NAS for RomM's var lib mysql. It is mounted into the container at /var/lib/mysql; RomM has full read and write access to it.
  type: path
- key: DB_PASSWD
  label: DB PASSWD
  type: string
- key: ROMM_AUTH_SECRET_KEY
  label: ROMM AUTH SECRET KEY
  type: password
volumes:
- container_path: /romm/resources
  label: Romm resources
  default_host_subpath: romm-romm-resources
- container_path: /redis-data
  label: Redis data
  default_host_subpath: romm-redis-data
- container_path: /romm/library
  label: Romm library
  default_host_subpath: romm-romm-library
- container_path: /romm/assets
  label: Romm assets
  default_host_subpath: romm-romm-assets
- container_path: /romm/config
  label: Romm config
  default_host_subpath: romm-romm-config
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: romm-db-var-lib-mysql
