services:
  threadfin:
    image: fyb3roptik/threadfin:1.2.37
    restart: unless-stopped
    ports:
      - 34400:34400
    volumes:
      - ${VOL_1}:/home/threadfin/conf/data
      - ${VOL_2}:/home/threadfin/conf/backup
    environment:
      - THREADFIN_BRANCH=main
      - THREADFIN_DEBUG=0
