id: libretranslate
name: LibreTranslate
author: Community
category: Developer
description: Free and Open Source Machine Translation API, entirely self-hosted. Unlike other APIs, it doesn't rely on proprietary providers such as Google or Azure to perform translations. Instead, its translation engine is powered by the open source Argos Translate library.
ugos:
  app_id: com.upkforge.docker.libretranslate
  version: 0.1.0
  port: 5000
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: App db folder
  help: Folder on the NAS for LibreTranslate's app db. It is mounted into the container at /app/db; LibreTranslate has full read and write access to it.
  label_de: App db-Ordner
  help_de: Ordner auf der NAS für LibreTranslates App db. Wird im Container unter /app/db eingebunden; LibreTranslate hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Home libretranslate .local folder
  help: Folder on the NAS for LibreTranslate's home libretranslate .local. It is mounted into the container at /home/libretranslate/.local; LibreTranslate has full read and write access to it.
  label_de: Home libretranslate .local-Ordner
  help_de: Ordner auf der NAS für LibreTranslates Home libretranslate .local. Wird im Container unter /home/libretranslate/.local eingebunden; LibreTranslate hat vollen Lese- und Schreibzugriff darauf.
  type: path
volumes:
- container_path: /app/db
  label: App db
  default_host_subpath: libretranslate-app-db
- container_path: /home/libretranslate/.local
  label: Home libretranslate .local
  default_host_subpath: libretranslate-home-libretranslate-local
