services:
  blinko:
    image: blinkospace/blinko:1.8.8
    restart: unless-stopped
    ports:
      - 1111:1111
    volumes:
      - ${VOL_1}:/app/.blinko
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:1111
      - NEXT_PUBLIC_BASE_URL=http://localhost:1111
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=postgresql://postgres:JWD9bxUR7Um9PaGg7FQZ@blinko-postgres:5432/postgres
  blinko-postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ${VOL_2}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=$TZ
