id: piwigo
name: Piwigo
author: Community
category: Media
description: Piwigo is a photo gallery software for the web that comes with powerful features to publish and manage your collection of pictures.
ugos:
  app_id: com.upkforge.docker.piwigo
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: media
parameters:
- key: VOL_1
  label: Config folder
  help: Folder on the NAS for Piwigo's config. It is mounted into the container at /config; Piwigo has full read and write access to it.
  label_de: Konfiguration-Ordner
  help_de: Ordner auf der NAS für Piwigos Konfiguration. Wird im Container unter /config eingebunden; Piwigo hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Gallery folder
  help: Folder on the NAS for Piwigo's gallery. It is mounted into the container at /gallery; Piwigo has full read and write access to it.
  label_de: Gallery-Ordner
  help_de: Ordner auf der NAS für Piwigos Gallery. Wird im Container unter /gallery eingebunden; Piwigo hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_3
  label: Var lib mysql folder
  help: Folder on the NAS for Piwigo's var lib mysql. It is mounted into the container at /var/lib/mysql; Piwigo has full read and write access to it.
  label_de: Var lib mysql-Ordner
  help_de: Ordner auf der NAS für Piwigos Var lib mysql. Wird im Container unter /var/lib/mysql eingebunden; Piwigo hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: MYSQL_ROOT_PASSWORD
  label: MYSQL ROOT PASSWORD
  type: password
- key: MYSQL_PASSWORD
  label: MYSQL PASSWORD
  type: password
volumes:
- container_path: /config
  label: Config
  default_host_subpath: piwigo-config
- container_path: /gallery
  label: Gallery
  default_host_subpath: piwigo-gallery
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: piwigo-db-var-lib-mysql
