id: farmos
name: FarmOS (Legacy)
author: Community
category: Social
description: farmOS is a web-based application for farm management, planning, and record keeping. It is developed by a community of volunteers and aims to provide a standard platform for farmers, developers, and researchers to build upon.
ugos:
  app_id: com.upkforge.docker.farmos
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Opt drupal web sites folder
  help: Folder on the NAS for FarmOS (Legacy)'s opt drupal web sites. It is mounted into the container at /opt/drupal/web/sites; FarmOS (Legacy) has full read and write access to it.
  label_de: Opt drupal web sites-Ordner
  help_de: Ordner auf der NAS für FarmOS (Legacy)s Opt drupal web sites. Wird im Container unter /opt/drupal/web/sites eingebunden; FarmOS (Legacy) hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib mysql folder
  help: Folder on the NAS for FarmOS (Legacy)'s var lib mysql. It is mounted into the container at /var/lib/mysql; FarmOS (Legacy) has full read and write access to it.
  label_de: Var lib mysql-Ordner
  help_de: Ordner auf der NAS für FarmOS (Legacy)s Var lib mysql. Wird im Container unter /var/lib/mysql eingebunden; FarmOS (Legacy) hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: MYSQL_ROOT_PASSWORD
  label: MYSQL ROOT PASSWORD
  type: password
volumes:
- container_path: /opt/drupal/web/sites
  label: Opt drupal web sites
  default_host_subpath: farmos-opt-drupal-web-sites
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: farmos-db-var-lib-mysql
