services:
  dashy-v4:
    image: lissy93/dashy:4.6.13
    restart: unless-stopped
    ports:
      - 4001:8080
    volumes:
      - ${VOL_1}:/app/user-data
    environment:
      - NODE_ENV=production
