services:
  prowlarr:
    image: linuxserver/prowlarr:2.5.2
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9696:9696
    volumes:
      - ${VOL_1}:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
