services:
  flowise:
    image: flowiseai/flowise:3.1.4
    restart: unless-stopped
    ports:
      - 3025:3025
    volumes:
      - ${VOL_1}:/root/.flowise
    environment:
      - PORT=3025
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
      - BLOB_STORAGE_PATH=/root/.flowise/storage
      - FLOWISE_USERNAME=${FLOWISE_PASSWORD}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
