services:
  albyhub:
    image: ghcr.io/getalby/hub:v1.24.0
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 58000:8080
    volumes:
      - ${VOL_1}:/data
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=$TZ
      - UMASK=002
      - WORK_DIR=/data/albyhub
      - LOG_EVENTS=true
