services:
  app:
    image: gtstef/filebrowser:1.5.1-stable@sha256:e82e3bb6d03d4c9e6d5b6ded452b202f79bad335490889591580bf350b601133
    restart: unless-stopped
    ports:
      - 8700:80
    volumes:
      - ./data:/home/filebrowser/data
      - ./srv:/srv
    environment:
      - TZ=UTC
