id: filebrowser-quantum
name: FileBrowser Quantum
author: Community
category: Productivity
description: A self-hosted web file manager forked from FileBrowser with advanced features including OIDC authentication, indexed search, office document previews, and multi-source support.
ugos:
  app_id: com.upkforge.docker.filebrowserquantum
  version: 0.1.0
  port: 8700
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Home filebrowser data folder
  help: Folder on the NAS for FileBrowser Quantum's home filebrowser data. It is mounted into the container at /home/filebrowser/data; FileBrowser Quantum has full read and write access to it.
  type: path
- key: VOL_2
  label: Srv folder
  help: Folder on the NAS for FileBrowser Quantum's srv. It is mounted into the container at /srv; FileBrowser Quantum has full read and write access to it.
  type: path
volumes:
- container_path: /home/filebrowser/data
  label: Home filebrowser data
  default_host_subpath: app-home-filebrowser-data
- container_path: /srv
  label: Srv
  default_host_subpath: app-srv
