services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.4
    restart: unless-stopped
    ports:
      - 8111:8443
      - 8112:8123
      - 19132:19132
    volumes:
      - ./backups:/crafty/backups
      - ./logs:/crafty/logs
      - ./servers:/crafty/servers
      - ./config:/crafty/app/config
      - ./import:/crafty/import
    environment:
      - TZ=Etc/UTC
