services:
  nextcloud-ls:
    image: linuxserver/nextcloud:34.0.4
    restart: unless-stopped
    ports:
      - 10443:443
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
