id: nextcloud-ls
name: Nextcloud LS
author: Community
category: Media
description: Nextcloud puts your data at your fingertips, under your control. Store your documents, calendar, contacts and photos on a server at home, at one of our providers or in a data center you trust.
ugos:
  app_id: com.upkforge.docker.nextcloudls
  version: 0.1.0
  port: 10443
  open_type: tab
  tag_type: media
volumes:
- container_path: /config
  label: Config
  user_chosen: false
  default_host_subpath: config
- container_path: /data
  label: Data
  user_chosen: false
  default_host_subpath: data
