services:
  app:
    image: gladysassistant/gladys:v5.0.4
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${VOL_1}:/var/run/docker.sock
      - ${VOL_2}:/var/lib/gladysassistant
      - /dev:/dev
      - /run/udev:/run/udev
    environment:
      - NODE_ENV=production
      - SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db
      - TZ=Europe/Paris
      - SERVER_PORT=1080
