services:
  pdfding:
    image: mrmn/pdfding:v1.14.0
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8000:8000
    volumes:
      - ${VOL_1}:/home/nonroot/pdfding/db
      - ${VOL_2}:/home/nonroot/pdfding/media
    environment:
      - HOST_NAME=*
      - SECRET_KEY=${SECRET_KEY}
      - CSRF_COOKIE_SECURE=FALSE
      - SESSION_COOKIE_SECURE=FALSE
      - DEBUG=FALSE
