id: pdfding
name: PdfDing
author: mrmn2
category: Productivity
description: PdfDing is a selfhosted PDF manager, viewer and editor offering a seamless user experience on multiple devices. It's designed to be minimal, fast, and easy to set up using Docker. With features like seamless browser-based PDF viewing that remembers your current position, multi-level tagging, starring and archiving functionalities, PDF editing with comments, highlighting and drawings, clean intuitive UI with dark mode, SSO support via OIDC, PDF sharing with external audience, markdown notes, and progress bars showing reading progress, PdfDing ensures an excellent PDF management experience. Deploying PdfDing on private cloud devices like brings unmatched convenience with multi-device access, ensuring your PDF collection is always within reach and secure, no matter where you are.
homepage: https://www.pdfding.com
source_code: https://github.com/mrmn2/PdfDing
ugos:
  app_id: com.upkforge.docker.pdfding
  version: 0.1.0
  port: 8000
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Home nonroot pdfding db folder
  help: Folder on the NAS for PdfDing's home nonroot pdfding db. It is mounted into the container at /home/nonroot/pdfding/db; PdfDing has full read and write access to it.
  type: path
- key: VOL_2
  label: Home nonroot pdfding media folder
  help: Folder on the NAS for PdfDing's home nonroot pdfding media. It is mounted into the container at /home/nonroot/pdfding/media; PdfDing has full read and write access to it.
  type: path
- key: SECRET_KEY
  label: SECRET KEY
  type: password
volumes:
- container_path: /home/nonroot/pdfding/db
  label: Home nonroot pdfding db
  default_host_subpath: pdfding-home-nonroot-pdfding-db
- container_path: /home/nonroot/pdfding/media
  label: Home nonroot pdfding media
  default_host_subpath: pdfding-home-nonroot-pdfding-media
