services:
  owncloud:
    image: owncloud/server:11.0.0
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ${VOL_1}:/mnt/data
    environment:
      - OWNCLOUD_DOMAIN=http://[YOUR_app_IP]:8080
      - OWNCLOUD_TRUSTED_DOMAINS=[YOUR_app_IP]
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=app_owncloud
      - OWNCLOUD_DB_USERNAME=app
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_DB_HOST=owncloud-db
      - OWNCLOUD_ADMIN_USERNAME=app
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=owncloud-redis
  owncloud-db:
    image: mariadb:10.6@sha256:114d40be36852d0a019afd8458f7e1cc63fd300403b115b1f32e31130d5f671b
    restart: unless-stopped
    command:
      - --max-allowed-packet=128M
      - --innodb-log-file-size=64M
    volumes:
      - ${VOL_2}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - MYSQL_USER=app
      - MYSQL_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=app_owncloud
      - MARIADB_AUTO_UPGRADE=1
  owncloud-redis:
    image: redis:8.10.1
    restart: unless-stopped
    command:
      - --databases
      - "1"
    volumes:
      - ${VOL_3}:/data
