id: owncloud
name: ownCloud
author: Community
category: Others
description: ownCloud offers file sharing and collaboration trusted by 200+ million users worldwide regardless of device or location.
ugos:
  app_id: com.upkforge.docker.owncloud
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Mnt data folder
  help: Folder on the NAS for ownCloud's mnt data. It is mounted into the container at /mnt/data; ownCloud has full read and write access to it.
  type: path
- key: VOL_2
  label: Var lib mysql folder
  help: Folder on the NAS for ownCloud's var lib mysql. It is mounted into the container at /var/lib/mysql; ownCloud has full read and write access to it.
  type: path
- key: VOL_3
  label: Data folder
  help: Folder on the NAS for ownCloud's data. It is mounted into the container at /data; ownCloud has full read and write access to it.
  type: path
- key: OWNCLOUD_DB_PASSWORD
  label: OWNCLOUD DB PASSWORD
  type: password
- key: OWNCLOUD_ADMIN_PASSWORD
  label: OWNCLOUD ADMIN PASSWORD
  type: password
volumes:
- container_path: /mnt/data
  label: Mnt data
  default_host_subpath: owncloud-mnt-data
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: owncloud-db-var-lib-mysql
- container_path: /data
  label: Data
  default_host_subpath: owncloud-redis-data
