services:
  dockpeek:
    image: ghcr.io/dockpeek/dockpeek:v1.7.3
    restart: unless-stopped
    ports:
      - 3420:8000
    volumes:
      - ${VOL_1}:/var/run/docker.sock
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - USERNAME=${PASSWORD}
      - PASSWORD=${PASSWORD}
      - DOCKER_HOST=unix:///var/run/docker.sock
