id: uptime-kuma
name: Uptime Kuma
version: 2.5.3
author: Uptime Kuma
category: System
description: >-
  Uptime Kuma is a free, easy-to-use self-hosted monitoring tool designed for real-time tracking of network services and infrastructure, offering a modern interface and robust functionality. It provides an intuitive Web dashboard for managing services, ideal for individual developers, home lab users, and small teams.


  The tool's core features include comprehensive monitoring and diverse notification channels. It monitors HTTP/HTTPS, TCP ports, DNS records, databases, Ping, and Steam game servers, with interactive Ping charts visually displaying response times and status. Users can receive real-time alerts via Telegram, Discord, Slack, Email (SMTP), and over 95 other notification services. SSL certificate monitoring checks certificate validity and expiration, aiding timely renewals.


  It supports 20-second monitoring intervals for rapid downtime detection and offers multiple status pages to share real-time service status with customers. Proxy support enables remote access via Cloudflare, Nginx, or similar services, enhancing flexibility. Two-factor authentication (2FA) and API keys bolster security, ensuring full user control over local data. The tool delivers an efficient monitoring solution with intuitive operation and community support.


  **Key Features:**

  - Monitor HTTP/HTTPS, TCP, DNS, databases, and other services

  - Notifications via Telegram, Discord, Slack, and over 95 other channels

  - Interactive Ping charts displaying response times and status

  - SSL certificate monitoring for validity and expiration

  - 20-second monitoring intervals for rapid downtime detection

  - Multiple status pages for sharing service status

  - Proxy support compatible with Cloudflare, Nginx, and more

  - Two-factor authentication (2FA) and API keys for enhanced security


  **Learn More:**

  - [Uptime Kuma Official Website](https://uptimekuma.org)

  - [Uptime Kuma GitHub Repository](https://github.com/louislam/uptime-kuma)
homepage: https://github.com/louislam/uptime-kuma
ugos:
  app_id: com.upkforge.docker.uptimekuma
  version: 0.1.0
  port: 3001
  open_type: tab
  tag_type: system
volumes:
- container_path: /app/data
  label: Data
  user_chosen: false
  default_host_subpath: config
