id: maybe-finance
name: Maybe Finance
author: Community
category: Finance
description: Maybe is a fully* open-source OS for your personal finances built by a small team alongside an incredible community Discord
ugos:
  app_id: com.upkforge.docker.maybefinance
  version: 0.1.0
  port: 4000
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Rails storage folder
  help: Folder on the NAS for Maybe Finance's rails storage. It is mounted into the container at /rails/storage; Maybe Finance has full read and write access to it.
  type: path
- key: VOL_2
  label: Var lib postgresql data folder
  help: Folder on the NAS for Maybe Finance's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; Maybe Finance has full read and write access to it.
  type: path
- key: VOL_3
  label: Data folder
  help: Folder on the NAS for Maybe Finance's data. It is mounted into the container at /data; Maybe Finance has full read and write access to it.
  type: path
- key: POSTGRES_PASSWORD
  label: POSTGRES PASSWORD
  type: password
volumes:
- container_path: /rails/storage
  label: Rails storage
  default_host_subpath: maybe-finance-rails-storage
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: maybe-finance-postgres-var-lib-postgresql-data
- container_path: /data
  label: Data
  default_host_subpath: maybe-finance-redis-data
