services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.23-s6@sha256:ee4ac79e52966a5f6247f99c7d667c1debfb277a3a61ab829f505aa8f4c74b21
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ${VOL_1}:/srv/app-data
      - ${VOL_2}:/srv/documents
      - ${VOL_3}:/srv/downloads
      - ${VOL_4}:/srv/gallery
      - ${VOL_5}:/srv/media
      - ${VOL_6}:/database
      - ${VOL_7}:/config
    environment:
      - PUID=0
      - PGID=0
