id: filebrowser
name: Filebrowser
author: Community
category: Others
description: Reliable and Performant File Management Desktop Sync and File Sharing Tool.
ugos:
  app_id: com.upkforge.docker.filebrowser
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Srv app data folder
  help: Folder on the NAS for Filebrowser's srv app data. It is mounted into the container at /srv/app-data; Filebrowser has full read and write access to it.
  type: path
- key: VOL_2
  label: Srv documents folder
  help: Folder on the NAS for Filebrowser's srv documents. It is mounted into the container at /srv/documents; Filebrowser has full read and write access to it.
  type: path
- key: VOL_3
  label: Srv downloads folder
  help: Folder on the NAS for Filebrowser's srv downloads. It is mounted into the container at /srv/downloads; Filebrowser has full read and write access to it.
  type: path
- key: VOL_4
  label: Srv gallery folder
  help: Folder on the NAS for Filebrowser's srv gallery. It is mounted into the container at /srv/gallery; Filebrowser has full read and write access to it.
  type: path
- key: VOL_5
  label: Srv media folder
  help: Folder on the NAS for Filebrowser's srv media. It is mounted into the container at /srv/media; Filebrowser has full read and write access to it.
  type: path
- key: VOL_6
  label: Database folder
  help: Folder on the NAS for Filebrowser's database. It is mounted into the container at /database; Filebrowser has full read and write access to it.
  type: path
- key: VOL_7
  label: Config folder
  help: Folder on the NAS for Filebrowser's config. It is mounted into the container at /config; Filebrowser has full read and write access to it.
  type: path
volumes:
- container_path: /srv/app-data
  label: Srv app data
  default_host_subpath: filebrowser-srv-app-data
- container_path: /srv/documents
  label: Srv documents
  default_host_subpath: filebrowser-srv-documents
- container_path: /srv/downloads
  label: Srv downloads
  default_host_subpath: filebrowser-srv-downloads
- container_path: /srv/gallery
  label: Srv gallery
  default_host_subpath: filebrowser-srv-gallery
- container_path: /srv/media
  label: Srv media
  default_host_subpath: filebrowser-srv-media
- container_path: /database
  label: Database
  default_host_subpath: filebrowser-database
- container_path: /config
  label: Config
  default_host_subpath: filebrowser-config
