services:
  lyrionmusicserver:
    image: lmscommunity/lyrionmusicserver:9.2.0
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9000:9000
      - 9090:9090
      - 3483:3483
      - 3483:3483
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/music
      - ${VOL_3}:/playlist
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - HTTP_PORT=9000
