services:
  lyrionmusicserver:
    image: lmscommunity/lyrionmusicserver:9.1.1
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9000:9000
      - 9090:9090
      - 3483:3483
      - 3483:3483
    volumes:
      - ./config:/config
      - ${VOL_1}:/music
      - ./playlists:/playlist
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - HTTP_PORT=9000
