services:
  jlesage-firefox:
    image: jlesage/firefox:v26.07.2@sha256:2bdbe30e355028eabb8a3a6f50a35a5d729e1de2376bc9c3c27c55fd2a7443d9
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ./config:/config
    environment:
      - VNC_PASSWORD=app
      - FF_OPEN_URL=https://community.app.com/
