services:
  jlesage-firefox:
    image: jlesage/firefox:v26.08.3
    restart: unless-stopped
    ports:
      - 5800:5800
    volumes:
      - ${VOL_1}:/config
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}
      - FF_OPEN_URL=https://community.app.com/
