id: pihole-unbound
name: Pi-hole and Unbound
author: Community
category: Networking
description: This is a custom pihole and unbound setup.
ugos:
  app_id: com.upkforge.docker.piholeunbound
  version: 0.1.0
  port: 53
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Etc pihole folder
  help: Folder on the NAS for Pi-hole and Unbound's etc pihole. It is mounted into the container at /etc/pihole/; Pi-hole and Unbound has full read and write access to it.
  type: path
- key: VOL_2
  label: Etc dnsmasq.d folder
  help: Folder on the NAS for Pi-hole and Unbound's etc dnsmasq.d. It is mounted into the container at /etc/dnsmasq.d/; Pi-hole and Unbound has full read and write access to it.
  type: path
- key: FTLCONF_webserver_api_password
  label: FTLCONF webserver api password
  type: password
volumes:
- container_path: /etc/pihole/
  label: Etc pihole
  default_host_subpath: app-etc-pihole
- container_path: /etc/dnsmasq.d/
  label: Etc dnsmasq.d
  default_host_subpath: app-etc-dnsmasq-d
