id: speedtest-tracker
name: Speedtest Tracker
author: Community
category: Networking
description: A Docker image to check your internet speed using Ookla's Speedtest service. Build using Laravel and the Speedtest CLI.
ugos:
  app_id: com.upkforge.docker.speedtesttracker
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Config folder
  help: Folder on the NAS for Speedtest Tracker's config. It is mounted into the container at /config; Speedtest Tracker has full read and write access to it.
  label_de: Konfiguration-Ordner
  help_de: Ordner auf der NAS für Speedtest Trackers Konfiguration. Wird im Container unter /config eingebunden; Speedtest Tracker hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Etc ssl web folder
  help: Folder on the NAS for Speedtest Tracker's etc ssl web. It is mounted into the container at /etc/ssl/web; Speedtest Tracker has full read and write access to it.
  label_de: Etc ssl web-Ordner
  help_de: Ordner auf der NAS für Speedtest Trackers Etc ssl web. Wird im Container unter /etc/ssl/web eingebunden; Speedtest Tracker hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_3
  label: Var lib mysql folder
  help: Folder on the NAS for Speedtest Tracker's var lib mysql. It is mounted into the container at /var/lib/mysql; Speedtest Tracker has full read and write access to it.
  label_de: Var lib mysql-Ordner
  help_de: Ordner auf der NAS für Speedtest Trackers Var lib mysql. Wird im Container unter /var/lib/mysql eingebunden; Speedtest Tracker hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: DB_PASSWORD
  label: DB PASSWORD
  type: password
- key: MARIADB_RANDOM_ROOT_PASSWORD
  label: MARIADB RANDOM ROOT PASSWORD
  type: password
volumes:
- container_path: /config
  label: Config
  default_host_subpath: speedtest-tracker-config
- container_path: /etc/ssl/web
  label: Etc ssl web
  default_host_subpath: speedtest-tracker-etc-ssl-web
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: speedtest-tracker-db-var-lib-mysql
