services:
  app:
    image: ghost:6.57.1-alpine@sha256:6e37900accfb12e16fbc15bf94500e09829cb17e6448b3051e9c76446b4fbf53
    restart: unless-stopped
    ports:
      - 2368:2368
    volumes:
      - ${VOL_1}:/var/lib/ghost/content
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=${database__connection__password}
      - database__connection__database=ghost
      - url=http://localhost:2368
  db:
    image: mysql:26.7.0
    restart: unless-stopped
    volumes:
      - ${VOL_2}:/var/lib/mysql
    environment:
      - MYSQL_USER=ghost
      - MYSQL_DATABASE=ghost
      - MYSQL_PASSWORD=${database__connection__password}
      - MYSQL_ROOT_PASSWORD=${database__connection__password}
