id: ghost
name: Ghost
author: Community
category: Others
description: Ghost is a free and open source blogging platform written in JavaScript and distributed under the MIT License, designed to simplify the process of online publishing for individual bloggers as well as online publications.
ugos:
  app_id: com.upkforge.docker.ghost
  version: 0.1.0
  port: 2368
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Var lib ghost content folder
  help: Folder on the NAS for Ghost's var lib ghost content. It is mounted into the container at /var/lib/ghost/content; Ghost has full read and write access to it.
  type: path
- key: VOL_2
  label: Var lib mysql folder
  help: Folder on the NAS for Ghost's var lib mysql. It is mounted into the container at /var/lib/mysql; Ghost has full read and write access to it.
  type: path
- key: database__connection__password
  label: Database connection password
  type: password
volumes:
- container_path: /var/lib/ghost/content
  label: Var lib ghost content
  default_host_subpath: app-var-lib-ghost-content
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: db-var-lib-mysql
