id: chatbot-ui
name: Chatbot UI
author: Team
category: AI
description: Chatbot UI is an open source chat UI for AI models.
homepage: https://www.chatbotui.com
source_code: https://github.com/mckaywrigley/chatbot-ui
ugos:
  app_id: com.upkforge.docker.chatbotui
  version: 0.1.0
  port: 3080
  open_type: tab
  tag_type: utility
