id: calcom
name: Cal.com
author: Community
category: Developer
description: >-
  The open source Calendly successor. You are in charge of your own data, workflow, and appearance.

  Calendly and other scheduling tools are awesome. It made our lives massively easier. We're using it for business meetings, seminars, yoga classes, and even calls with our families. However, most tools are very limited in terms of control and customization.
      That's where Cal.com comes in. Self-hosted or hosted by us. White-label by design. API-driven and ready to be deployed on your own domain. Full control of your events and data.
ugos:
  app_id: com.upkforge.docker.calcom
  version: 0.1.0
  port: 3000
  open_type: tab
  tag_type: devtool
parameters:
- key: POSTGRES_PASSWORD
  label: POSTGRES PASSWORD
  type: password
- key: NEXTAUTH_SECRET
  label: NEXTAUTH SECRET
  type: password
- key: CALENDSO_ENCRYPTION_KEY
  label: CALENDSO ENCRYPTION KEY
  type: password
volumes:
- container_path: /config
  label: Config
  user_chosen: false
  default_host_subpath: config
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  user_chosen: false
  default_host_subpath: data/db
