id: calcom
name: Cal.com
author: Community
category: Developer
description: >-
  The open source Calendly successor. You are in charge of your own data, workflow, and appearance.

  Calendly and other scheduling tools are awesome. It made our lives massively easier. We're using it for business meetings, seminars, yoga classes, and even calls with our families. However, most tools are very limited in terms of control and customization.
      That's where Cal.com comes in. Self-hosted or hosted by us. White-label by design. API-driven and ready to be deployed on your own domain. Full control of your events and data.
ugos:
  app_id: com.upkforge.docker.calcom
  version: 0.1.0
  port: 3000
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Config folder
  help: Folder on the NAS for Cal.com's config. It is mounted into the container at /config; Cal.com has full read and write access to it.
  label_de: Konfiguration-Ordner
  help_de: Ordner auf der NAS für Cal.coms Konfiguration. Wird im Container unter /config eingebunden; Cal.com hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib postgresql data folder
  help: Folder on the NAS for Cal.com's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; Cal.com has full read and write access to it.
  label_de: Var lib postgresql Daten-Ordner
  help_de: Ordner auf der NAS für Cal.coms Var lib postgresql Daten. Wird im Container unter /var/lib/postgresql/data eingebunden; Cal.com hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: POSTGRES_PASSWORD
  label: POSTGRES PASSWORD
  type: password
- key: NEXTAUTH_SECRET
  label: NEXTAUTH SECRET
  type: password
- key: CALENDSO_ENCRYPTION_KEY
  label: CALENDSO ENCRYPTION KEY
  type: password
volumes:
- container_path: /config
  label: Config
  default_host_subpath: calcom-config
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: calcom-db-var-lib-postgresql-data
