services:
  cloudflared-web:
    image: wisdomsky/cloudflared-web:2026.7.3@sha256:b6f14046f7da3286fb071ade58fff377da847661ff7506fd8f95f8a43f8350b0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/config
    environment:
      - WEBUI_PORT=14333
      - EDGE_IP_VERSION=auto
      - PROTOCOL=auto
      - METRICS_ENABLE=false
      - METRICS_PORT=60123
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
