services:
  cloudflared-web:
    image: wisdomsky/cloudflared-web:2026.9.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${VOL_1}:/config
    environment:
      - WEBUI_PORT=14333
      - EDGE_IP_VERSION=auto
      - PROTOCOL=auto
      - METRICS_ENABLE=false
      - METRICS_PORT=60123
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
