services:
  ncdu:
    image: bigbeartechworld/big-bear-ncdu:0.0.9@sha256:d48a75e108f9387393265eefc2e99564e4b717a78f5207d000ebe619e8ff05b3
    restart: unless-stopped
    ports:
      - 7681:7681
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - ./ncdu-app:/app
    environment:
      - NCDU_PATH=/
