id: teable
name: Teable
author: teableio
category: Productivity
description: >-
  Teable is a new generation open-source database platform. It provides an intuitive spreadsheet-like experience, while being powered by a high-performance Postgres database underneath, combining ease of use with powerful data processing capabilities.


  **Key Features:**

  - **High Performance**: Built on the Postgres core, it effortlessly handles millions of records with extremely fast response times.

  - **Modern Interface**: Offers multiple views including grid, kanban, gallery, and forms, with a clean and user-friendly design.

  - **Real-time Collaboration**: Supports multi-user online collaboration with real-time data synchronisation.

  - **Automation & API**: Provides powerful RESTful APIs to enable flexible integration and automation.


  **Learn More:**

  - [Teable Official Website](https://teable.ai)

  - [Teable GitHub Repository](https://github.com/teableio/teable)

  - [Help Documentation](https://help.teable.ai)
homepage: https://teable.ai
source_code: https://github.com/teableio/teable
ugos:
  app_id: com.upkforge.docker.teable
  version: 0.1.0
  port: 3200
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: App .assets folder
  help: Folder on the NAS for Teable's app .assets. It is mounted into the container at /app/.assets; Teable has full read and write access to it.
  type: path
- key: VOL_2
  label: Var lib postgresql data folder
  help: Folder on the NAS for Teable's var lib postgresql data. It is mounted into the container at /var/lib/postgresql/data; Teable has full read and write access to it.
  type: path
- key: VOL_3
  label: Data folder
  help: Folder on the NAS for Teable's data. It is mounted into the container at /data; Teable has full read and write access to it.
  type: path
- key: POSTGRES_PASSWORD
  label: POSTGRES PASSWORD
  type: password
volumes:
- container_path: /app/.assets
  label: App .assets
  default_host_subpath: teable-app-assets
- container_path: /var/lib/postgresql/data
  label: Var lib postgresql data
  default_host_subpath: teable-db-var-lib-postgresql-data
- container_path: /data
  label: Data
  default_host_subpath: teable-cache-data
