services:
  wallabag:
    image: wallabag/wallabag:2.6.14
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 25661:80
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=http://<IP>:25661
      - SYMFONY__ENV__SERVER_NAME=Wallabag
