services:
  app:
    image: ghcr.io/donkie/spoolman:0.26.1
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7912:8000
    volumes:
      - ${VOL_1}:/home/app/.local/share/spoolman
    environment:
      - TZ=$TZ
      - SPOOLMAN_DB_TYPE=sqlite
      - SPOOLMAN_LOGGING_LEVEL=INFO
      - SPOOLMAN_AUTOMATIC_BACKUP=TRUE
