services:
  mineos:
    image: hexparrot/mineos:node-wily
    restart: unless-stopped
    ports:
      - 8444:8443
    volumes:
      - ${VOL_1}:/var/games/minecraft
    environment:
      - USE_HTTPS=true
      - SERVER_PORT=8443
      - USER_NAME=mc
      - USER_UID=1000
      - USER_PASSWORD=${USER_PASSWORD}
