services:
  virt-manager:
    image: mber5/virt-manager:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8185:80
    volumes:
      - ${VOL_1}:/var/run/libvirt/libvirt-sock
      - ${VOL_2}:/var/lib/libvirt
      - ${VOL_3}:/DATA/Downloads
    environment:
      - DARK_MODE=false
      - HOSTS=['qemu:///system']
