services:
  postgresql:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ${VOL_1}:/var/lib/postgresql/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
