services:
  psitransfer:
    image: psitrax/psitransfer:v2.4.1
    restart: unless-stopped
    ports:
      - 13001:3000
    volumes:
      - ./data:/data
    environment:
      - PSITRANSFER_ADMIN_PASS=${PSITRANSFER_ADMIN_PASS}
