id: upsnap
name: Upsnap
author: Community
category: Others
description: A simple wake on lan web app written with SvelteKit, Go and PocketBase.
warnings:
- service uses host networking
ugos:
  app_id: com.upkforge.docker.upsnap
  version: 0.1.0
  port: 8090
  open_type: tab
  tag_type: utility
volumes:
- container_path: /app/pb_data
  label: App pb data
  user_chosen: false
  default_host_subpath: pb/data
