id: matterbridge
name: Matterbridge
author: Community
category: Home
description: Matterbridge is a Matter plugin manager that allows you to have all your Matter devices up and running in a couple of minutes without having to deal with the pairing process for each individual device. It creates a device that can be paired with any ecosystem, such as Apple Home, Google Home, Amazon Alexa, Home Assistant, or any other platform supporting Matter.
warnings:
- service uses host networking
ugos:
  app_id: com.upkforge.docker.matterbridge
  version: 0.1.0
  port: 8283
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Root Matterbridge folder
  help: Folder on the NAS for Matterbridge's root matterbridge. It is mounted into the container at /root/Matterbridge; Matterbridge has full read and write access to it.
  type: path
- key: VOL_2
  label: Root .matterbridge folder
  help: Folder on the NAS for Matterbridge's root .matterbridge. It is mounted into the container at /root/.matterbridge; Matterbridge has full read and write access to it.
  type: path
volumes:
- container_path: /root/Matterbridge
  label: Root Matterbridge
  default_host_subpath: matterbridge-root-matterbridge
- container_path: /root/.matterbridge
  label: Root .matterbridge
  default_host_subpath: matterbridge-root-matterbridge
