id: pterodactyl-panel
name: Pterodactyl Panel
author: Community
category: Developer
description: Pterodactyl® is a free, open-source game server management panel built with PHP, React, and Go. Designed with security in mind, Pterodactyl runs all game servers in isolated Docker containers while exposing a beautiful and intuitive UI to end users.
ugos:
  app_id: com.upkforge.docker.pterodactylpanel
  version: 0.1.0
  port: 1180
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: App var folder
  help: Folder on the NAS for Pterodactyl Panel's app var. It is mounted into the container at /app/var/; Pterodactyl Panel has full read and write access to it.
  type: path
- key: VOL_2
  label: Etc nginx http.d folder
  help: Folder on the NAS for Pterodactyl Panel's etc nginx http.d. It is mounted into the container at /etc/nginx/http.d/; Pterodactyl Panel has full read and write access to it.
  type: path
- key: VOL_3
  label: Etc letsencrypt folder
  help: Folder on the NAS for Pterodactyl Panel's etc letsencrypt. It is mounted into the container at /etc/letsencrypt/; Pterodactyl Panel has full read and write access to it.
  type: path
- key: VOL_4
  label: App storage logs folder
  help: Folder on the NAS for Pterodactyl Panel's app storage logs. It is mounted into the container at /app/storage/logs; Pterodactyl Panel has full read and write access to it.
  type: path
- key: VOL_5
  label: Var lib mysql folder
  help: Folder on the NAS for Pterodactyl Panel's var lib mysql. It is mounted into the container at /var/lib/mysql; Pterodactyl Panel has full read and write access to it.
  type: path
- key: DB_PASSWORD
  label: DB PASSWORD
  type: password
volumes:
- container_path: /app/var/
  label: App var
  default_host_subpath: app-app-var
- container_path: /etc/nginx/http.d/
  label: Etc nginx http.d
  default_host_subpath: app-etc-nginx-http-d
- container_path: /etc/letsencrypt/
  label: Etc letsencrypt
  default_host_subpath: app-etc-letsencrypt
- container_path: /app/storage/logs
  label: App storage logs
  default_host_subpath: app-app-storage-logs
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: database-var-lib-mysql
