services:
  emby:
    image: emby/embyserver:4.10.0.40
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/data/tvshows
      - ${VOL_3}:/data/movies
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
      - TZ=$TZ
      - NVIDIA_VISIBLE_DEVICES=all
