id: emby-nvidia
name: Emby(Nvidia GPU)
author: Team
category: Media
description: Bringing all of your home videos, music, and photos together into one place has never been easier. Your personal Emby Server automatically converts and streams your media on-the-fly to play on any device.
homepage: https://emby.media/
source_code: https://github.com/linuxserver/docker-emby
ugos:
  app_id: com.upkforge.docker.embynvidia
  version: 0.1.0
  port: 8096
  open_type: tab
  tag_type: media
parameters:
- key: VOL_1
  label: Data tvshows folder
  help: Folder on the NAS for Emby(Nvidia GPU)'s data tvshows. It is mounted into the container at /data/tvshows; Emby(Nvidia GPU) has full read and write access to it.
  type: path
- key: VOL_2
  label: Data movies folder
  help: Folder on the NAS for Emby(Nvidia GPU)'s data movies. It is mounted into the container at /data/movies; Emby(Nvidia GPU) has full read and write access to it.
  type: path
volumes:
- container_path: /config
  label: Config
  user_chosen: false
  default_host_subpath: config
- container_path: /data/tvshows
  label: Data tvshows
  default_host_subpath: emby-data-tvshows
- container_path: /data/movies
  label: Data movies
  default_host_subpath: emby-data-movies
