services:
  visor-ui:
    image: docker.io/lijiahangmax/orion-visor-ui:2.5.7
    ports:
      - "1081:80"
    environment:
      - NGINX_SERVICE_HOST=visor-service
      - NGINX_SERVICE_PORT=9200
    depends_on:
      visor-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - visor-net

  visor-service:
    image: docker.io/lijiahangmax/orion-visor-service:2.5.7
    privileged: true
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=visor-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=orion_visor
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=visor-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=0
      - REDIS_DATA_VERSION=1
      - INFLUXDB_ENABLED=true
      - INFLUXDB_HOST=visor-influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_ORG=orion-visor
      - INFLUXDB_BUCKET=metrics
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - GUACD_HOST=visor-guacd
      - GUACD_PORT=4822
      - GUACD_DRIVE_PATH=/drive
      - SECRET_KEY=${SECRET_KEY}
      - API_EXPOSE_TOKEN=${API_EXPOSE_TOKEN}
      - API_IP_HEADERS=X-Forwarded-For,X-Real-IP
      - API_HOST=API_HOST__
      - API_CORS=true
      - DEMO_MODE=false
    volumes:
      - ./volumes/service/root-orion:/root/orion
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:9200/orion-visor/api/server/bootstrap/health"]
      interval: 15s
      timeout: 5s
      retries: 15
      start_period: 60s
    depends_on:
      visor-mysql:
        condition: service_healthy
      visor-redis:
        condition: service_healthy
      visor-influxdb:
        condition: service_healthy
    networks:
      - visor-net

  visor-mysql:
    image: docker.io/lijiahangmax/orion-visor-mysql:2.5.7
    privileged: true
    environment:
      - MYSQL_DATABASE=orion_visor
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/mysql/var-lib-mysql:/var/lib/mysql
      - ./volumes/mysql/var-lib-mysql-files:/var/lib/mysql-files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/3306"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - visor-net

  visor-redis:
    image: docker.io/lijiahangmax/orion-visor-redis:2.5.7
    privileged: true
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./volumes/redis/data:/data
    command: sh -c "redis-server /usr/local/redis.conf --requirepass __REDIS_PASSWORD__"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - visor-net

  visor-influxdb:
    image: docker.io/lijiahangmax/orion-visor-influxdb:2.5.7
    privileged: true
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=orion-visor
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb2
      - ./volumes/influxdb/config:/etc/influxdb2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8086"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - visor-net

  visor-guacd:
    image: docker.io/lijiahangmax/orion-visor-guacd:2.5.7
    environment:
      - GUACD_LOG_LEVEL=info
      - GUACD_LOG_FILE=/var/log/guacd.log
    volumes:
      - ./volumes/guacd/drive:/drive
      - ./volumes/guacd/var-logs:/var/log
      - ./volumes/guacd/local-guacamole-lib:/usr/local/guacamole/lib
      - ./volumes/guacd/local-guacamole-extensions:/usr/local/guacamole/extensions
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "4822"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - visor-net

networks:
  visor-net:
    driver: bridge
