services:
  app:
    image: baserow/baserow:2.3.3@sha256:41adb3493379403946a493f30873f743bb65b19b5f387d630ec75f41e25d5b5b
    restart: unless-stopped
    ports:
      - 7350:80
      - 7351:443
    volumes:
      - ${VOL_1}:/baserow/data
    environment:
      - BASEROW_PUBLIC_URL=http://[YOUR_app_IP]:7350
