id: baserow
name: Baserow
author: Community
category: Developer
description: Create your own online database without technical experience. Our user-friendly no-code tool gives you the powers of a developer without leaving your browser.
ugos:
  app_id: com.upkforge.docker.baserow
  version: 0.1.0
  port: 7350
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Baserow data folder
  help: Folder on the NAS for Baserow's baserow data. It is mounted into the container at /baserow/data; Baserow has full read and write access to it.
  label_de: Baserow Daten-Ordner
  help_de: Ordner auf der NAS für Baserows Baserow Daten. Wird im Container unter /baserow/data eingebunden; Baserow hat vollen Lese- und Schreibzugriff darauf.
  type: path
volumes:
- container_path: /baserow/data
  label: Baserow data
  default_host_subpath: app-baserow-data
