services:
  mongodb4:
    image: mongo:8.3.9
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ${VOL_1}:/data/configdb
      - ${VOL_2}:/data/db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
