id: mongodb4
name: MongoDB 4
author: WisdomSky
category: Developer
description: MongoDB is a free and open-source cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with schemata. MongoDB is developed by MongoDB Inc., and is published under a combination of the Server Side Public License and the Apache License.
homepage: https://www.mongodb.com/
source_code: https://github.com/mongodb/mongo
ugos:
  app_id: com.upkforge.docker.mongodb4
  version: 0.1.0
  port: 27017
  open_type: tab
  tag_type: devtool
parameters:
- key: VOL_1
  label: Data configdb folder
  help: Folder on the NAS for MongoDB 4's data configdb. It is mounted into the container at /data/configdb; MongoDB 4 has full read and write access to it.
  label_de: Daten configdb-Ordner
  help_de: Ordner auf der NAS für MongoDB 4s Daten configdb. Wird im Container unter /data/configdb eingebunden; MongoDB 4 hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Data db folder
  help: Folder on the NAS for MongoDB 4's data db. It is mounted into the container at /data/db; MongoDB 4 has full read and write access to it.
  label_de: Daten db-Ordner
  help_de: Ordner auf der NAS für MongoDB 4s Daten db. Wird im Container unter /data/db eingebunden; MongoDB 4 hat vollen Lese- und Schreibzugriff darauf.
  type: path
volumes:
- container_path: /data/configdb
  label: Data configdb
  default_host_subpath: mongodb4-data-configdb
- container_path: /data/db
  label: Data db
  default_host_subpath: mongodb4-data-db
