services:
  app:
    image: mrcas/mind:v1.4.1@sha256:152f824d093f2e8772af0d209afc710b9e79edf3e6286d7c3eccb0509dafffd4
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./db:/app/db
    environment:
      - TZ=UTC
