id: mind
name: MIND
author: Community
category: Others
description: A simple self hosted reminder application that can send push notifications to your device. Set the reminder and forget about it!
ugos:
  app_id: com.upkforge.docker.mind
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: App db folder
  help: Folder on the NAS for MIND's app db. It is mounted into the container at /app/db; MIND has full read and write access to it.
  type: path
volumes:
- container_path: /app/db
  label: App db
  default_host_subpath: app-app-db
