services:
  adguard-home-host:
    image: adguard/adguardhome:v0.107.79
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${VOL_1}:/opt/adguardhome/work
      - ${VOL_2}:/opt/adguardhome/conf
