services:
  zipline:
    image: ghcr.io/diced/zipline:3.7.13@sha256:f0209223b159be9460bf1454b1908417877fef6a1f3a31d5e682885fb9431f30
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/zipline/uploads
      - ./public:/zipline/public
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=${CORE_SECRET}
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgrespassword@zipline-db/zipline
      - CORE_LOGGER=true
  zipline-db:
    image: postgres:15@sha256:bcab099bfaab33333a73a2ebe8c1d615c9f4c2402dd43452f989a36c6da9a5ba
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=zipline
