services:
  kopia:
    image: ghcr.io/thespad/kopia-server:v0.17.0-spad3@sha256:e9e9256e0037030932b78a16bdef09894b6f9c6f89e8367e05d9777813e67f62
    restart: unless-stopped
    ports:
      - 51515:51515
    volumes:
      - ${VOL_1}:/config
      - ${VOL_2}:/backups/home
      - ${VOL_3}:/backups/docker
      - ${VOL_4}:/repository
      - /tmp:/tmp
      - ${VOL_5}:/var/run/docker.sock
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - KOPIA_HTTPS=true
      - KOPIA_UI_USERNAME=${KOPIA_UI_PASSWORD}
      - KOPIA_UI_PASSWORD=${KOPIA_UI_PASSWORD}
      - KOPIA_PASSWORD=${KOPIA_UI_PASSWORD}
      - REFRESH_INTERVAL=
