id: kopia
name: Kopia
author: Community
category: Networking
description: Kopia is a fast and secure open-source backup/restore tool that allows you to create encrypted snapshots of your data and save the snapshots to remote or cloud storage of your choice, to network-attached storage or server, or locally on your machine.
warnings:
- 'service adds capabilities: SYS_ADMIN'
ugos:
  app_id: com.upkforge.docker.kopia
  version: 0.1.0
  port: 51515
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Config folder
  help: Folder on the NAS for Kopia's config. It is mounted into the container at /config; Kopia has full read and write access to it.
  type: path
- key: VOL_2
  label: Backups home folder
  help: Folder on the NAS for Kopia's backups home. It is mounted into the container at /backups/home; Kopia has full read and write access to it.
  type: path
- key: VOL_3
  label: Backups docker folder
  help: Folder on the NAS for Kopia's backups docker. It is mounted into the container at /backups/docker; Kopia has full read and write access to it.
  type: path
- key: VOL_4
  label: Repository folder
  help: Folder on the NAS for Kopia's repository. It is mounted into the container at /repository; Kopia has full read and write access to it.
  type: path
- key: VOL_5
  label: Var run docker.sock folder
  help: Folder on the NAS for Kopia's var run docker.sock. It is mounted into the container at /var/run/docker.sock; Kopia has full read and write access to it.
  type: path
- key: KOPIA_UI_PASSWORD
  label: KOPIA UI PASSWORD
  type: password
volumes:
- container_path: /config
  label: Config
  default_host_subpath: kopia-config
- container_path: /backups/home
  label: Backups home
  default_host_subpath: kopia-backups-home
- container_path: /backups/docker
  label: Backups docker
  default_host_subpath: kopia-backups-docker
- container_path: /repository
  label: Repository
  default_host_subpath: kopia-repository
- container_path: /var/run/docker.sock
  label: Var run docker.sock
  default_host_subpath: kopia-var-run-docker-sock
