services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.16.1
    restart: unless-stopped
    ports:
      - 3051:3001
    volumes:
      - ${VOL_1}:/app/server/storage
    environment:
      - STORAGE_DIR=/app/server/storage
