services:
  openlist:
    image: openlistteam/openlist:v4.2.6
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5244:5244
    volumes:
      - ${VOL_1}:/opt/openlist/data
    environment:
      - UMASK=022
      - OPENLIST_ADMIN_PASSWORD=${OPENLIST_ADMIN_PASSWORD}
