services:
  photoprism:
    image: docker.io/photoprism/photoprism:260728
    ports:
      - "2342:2342"
    volumes:
      - ./storage:/photoprism/storage
      - ./originals:/photoprism/originals
    environment:
      - TZ=${TZ}
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_SITE_URL=http://localhost:2342
    restart: unless-stopped
