id: semaphore
name: Ansible Semaphore
author: Community
category: Others
description: Ansible Semaphore is a modern UI for Ansible. It lets you easily run Ansible playbooks, get notifications about fails, control access to deployment system.
ugos:
  app_id: com.upkforge.docker.semaphore
  version: 0.1.0
  port: 3000
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Etc semaphore folder
  help: Folder on the NAS for Ansible Semaphore's etc semaphore. It is mounted into the container at /etc/semaphore; Ansible Semaphore has full read and write access to it.
  label_de: Etc semaphore-Ordner
  help_de: Ordner auf der NAS für Ansible Semaphores Etc semaphore. Wird im Container unter /etc/semaphore eingebunden; Ansible Semaphore hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib semaphore folder
  help: Folder on the NAS for Ansible Semaphore's var lib semaphore. It is mounted into the container at /var/lib/semaphore; Ansible Semaphore has full read and write access to it.
  label_de: Var lib semaphore-Ordner
  help_de: Ordner auf der NAS für Ansible Semaphores Var lib semaphore. Wird im Container unter /var/lib/semaphore eingebunden; Ansible Semaphore hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_3
  label: Var lib mysql folder
  help: Folder on the NAS for Ansible Semaphore's var lib mysql. It is mounted into the container at /var/lib/mysql; Ansible Semaphore has full read and write access to it.
  label_de: Var lib mysql-Ordner
  help_de: Ordner auf der NAS für Ansible Semaphores Var lib mysql. Wird im Container unter /var/lib/mysql eingebunden; Ansible Semaphore hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: SEMAPHORE_DB_PASS
  label: SEMAPHORE DB PASS
  type: string
- key: SEMAPHORE_ADMIN_PASSWORD
  label: SEMAPHORE ADMIN PASSWORD
  type: password
- key: MYSQL_RANDOM_ROOT_PASSWORD
  label: MYSQL RANDOM ROOT PASSWORD
  type: password
volumes:
- container_path: /etc/semaphore
  label: Etc semaphore
  default_host_subpath: semaphore-etc-semaphore
- container_path: /var/lib/semaphore
  label: Var lib semaphore
  default_host_subpath: semaphore-var-lib-semaphore
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: semaphore-db-var-lib-mysql
