services:
  ztnet:
    image: docker.io/sinamics/ztnet:0.8.3
    working_dir: /app
    depends_on:
      - postgres
      - zerotier
    ports:
      - "3008:3000"
    volumes:
      - ./ztnet:/app/data
      - ./zerotier:/var/lib/zerotier-one
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${wizard_postgres_password}
      - POSTGRES_DB=ztnet
      - NEXTAUTH_URL=${wizard_nextauth_url}
      - NEXTAUTH_SECRET=${wizard_nextauth_secret}
      - NEXTAUTH_URL_INTERNAL=http://ztnet:3000
      - ZT_ADDR=http://zerotier:9993
      - ZT_SECRET=${wizard_zt_secret}
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: docker.io/postgres:15.2-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${wizard_postgres_password}
      - POSTGRES_DB=ztnet
    networks:
      - app-network
    restart: unless-stopped

  zerotier:
    image: docker.io/zyclonite/zerotier:1.16.2
    hostname: zerotier
    volumes:
      - ./zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "9993:9993/udp"
    environment:
      - TZ=${TZ}
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
