services:
  pingvin-share:
    image: stonith404/pingvin-share:v1.13.0
    restart: unless-stopped
    ports:
      - 3410:3000
    volumes:
      - ${VOL_1}:/opt/app/backend/data
      - ${VOL_2}:/opt/app/frontend/public/img
    environment:
      - TRUST_PROXY=false
