id: financial-freedom
name: Financial Freedom
author: Community
category: Others
description: Keep investors and their buyers out of your financial data. Own 100% of your data and start building financial wealth.
ugos:
  app_id: com.upkforge.docker.financialfreedom
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Var www html storage logs folder
  help: Folder on the NAS for Financial Freedom's var www html storage logs. It is mounted into the container at /var/www/html/storage/logs; Financial Freedom has full read and write access to it.
  type: path
- key: VOL_2
  label: Var www html storage framework sessions folder
  help: Folder on the NAS for Financial Freedom's var www html storage framework sessions. It is mounted into the container at /var/www/html/storage/framework/sessions; Financial Freedom has full read and write access to it.
  type: path
- key: VOL_3
  label: Var lib mysql folder
  help: Folder on the NAS for Financial Freedom's var lib mysql. It is mounted into the container at /var/lib/mysql; Financial Freedom has full read and write access to it.
  type: path
- key: APP_KEY
  label: APP KEY
  type: password
- key: DB_ROOT_PASSWORD
  label: DB ROOT PASSWORD
  type: password
- key: MAIL_PASSWORD
  label: MAIL PASSWORD
  type: password
- key: MYSQL_ROOT_PASSWORD
  label: MYSQL ROOT PASSWORD
  type: password
volumes:
- container_path: /var/www/html/storage/logs
  label: Var www html storage logs
  default_host_subpath: app-var-www-html-storage-logs
- container_path: /var/www/html/storage/framework/sessions
  label: Var www html storage framework sessions
  default_host_subpath: app-var-www-html-storage-framework-sessions
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: mariadb-var-lib-mysql
