services:
  app:
    image: rocket.chat:8.5.1@sha256:2c41afc6b30ca822d81dba2c3121484ee30ecd009be549d7dd521ef0eb061f1c
    restart: unless-stopped
    ports:
      - 3100:3000
    environment:
      - MONGO_OPLOG_URL=mongodb://db:27017/local
      - ROOT_URL=http://localhost:3100
  db:
    image: mongo:8.2.0
    restart: unless-stopped
    volumes:
      - ${VOL_1}:/data/db
