services:
  broker:
    image: docker.io/library/valkey:9-alpine
    restart: unless-stopped
  db:
    volumes:
      - ./paperless/db:/var/lib/postgresql/data
    image: docker.io/library/postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  webserver:
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      - ${VOL_1}:/usr/src/paperless/media
      - ${VOL_2}:/usr/src/paperless/consume
    image: ghcr.io/paperless-ngx/paperless-ngx:3.1.3
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
      TZ: ${TZ}