services:
  redis:
    image: docker.io/library/redis:7-alpine
    restart: unless-stopped

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:3.1.3
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      - PAPERLESS_REDIS=redis://redis:6379
      - PAPERLESS_DBENGINE=sqlite
      - PAPERLESS_PORT=8000
      - PAPERLESS_URL=http://localhost:8000
      - TZ=${TZ}
    restart: unless-stopped
