id: open-webui
name: Open WebUI
version: 0.11.3
author: open-webui
category: Ai
description: >-
  Open WebUI is a feature-rich, user-friendly self-hosted AI platform designed for fully offline operation, supporting multiple large language model runners and API integration. Its intuitive Web interface provides powerful AI deployment capabilities, ideal for developers, researchers, and AI enthusiasts building localized intelligent applications.


  The tool's core features include local model execution and Retrieval Augmented Generation (RAG). It supports Ollama and OpenAI-compatible APIs (e.g., LMStudio, GroqCloud), enabling seamless model switching and multi-model conversations. RAG enhances chat experiences through local document loading or web search integration (e.g., SearXNG, Google PSE). Granular permissions and role-based access control (RBAC) ensure security with customized user role management.


  It supports Markdown and LaTeX for enriched interactions and offers hands-free voice and video call features for dynamic communication. Image generation integration (e.g., DALL-E, ComfyUI) enriches visual content, and a model builder enables creating and importing custom models via the interface. The Pipelines plugin framework supports Python plugins, extending functionality like function calling and real-time translation. The tool’s offline privacy and flexibility deliver a modern AI interaction solution.


  **Key Features:**

  - Local execution of Ollama and OpenAI-compatible APIs with multi-model conversations

  - RAG support with local document and web search integration (e.g., SearXNG, Google PSE)

  - Granular permissions and role-based access control (RBAC)

  - Simultaneous interaction with multiple models, leveraging their strengths

  - Image generation integration with DALL-E, ComfyUI, and more

  - Full Markdown and LaTeX support

  - Hands-free voice and video call functionality

  - Pipelines plugin framework for custom Python functionality


  **Learn More:**

  - [Open WebUI Official Website](https://openwebui.com)

  - [Open WebUI Documentation](https://docs.openwebui.com)

  - [Open WebUI GitHub Repository](https://github.com/open-webui/open-webui)
homepage: https://github.com/open-webui/open-webui
ugos:
  app_id: com.upkforge.docker.openwebui
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: WEBUI_SECRET_KEY
  label: Webui secret key
  type: password
  changeable: false
  generate_bytes: 24
volumes:
- container_path: /app/backend/data
  label: Data
  user_chosen: false
  default_host_subpath: data
