id: wordpress
name: WordPress (Legacy)
author: Community
category: Others
description: Initially started as a blogging tool in 2003, it has evolved into a highly flexible CMS that powers over 40% of the web (as of my last training data in 2022).
ugos:
  app_id: com.upkforge.docker.wordpress
  version: 0.1.0
  port: 8080
  open_type: tab
  tag_type: utility
parameters:
- key: VOL_1
  label: Var www html folder
  help: Folder on the NAS for WordPress (Legacy)'s var www html. It is mounted into the container at /var/www/html; WordPress (Legacy) has full read and write access to it.
  label_de: Var www html-Ordner
  help_de: Ordner auf der NAS für WordPress (Legacy)s Var www html. Wird im Container unter /var/www/html eingebunden; WordPress (Legacy) hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: VOL_2
  label: Var lib mysql folder
  help: Folder on the NAS for WordPress (Legacy)'s var lib mysql. It is mounted into the container at /var/lib/mysql; WordPress (Legacy) has full read and write access to it.
  label_de: Var lib mysql-Ordner
  help_de: Ordner auf der NAS für WordPress (Legacy)s Var lib mysql. Wird im Container unter /var/lib/mysql eingebunden; WordPress (Legacy) hat vollen Lese- und Schreibzugriff darauf.
  type: path
- key: WORDPRESS_DB_PASSWORD
  label: WORDPRESS DB PASSWORD
  type: password
volumes:
- container_path: /var/www/html
  label: Var www html
  default_host_subpath: app-var-www-html
- container_path: /var/lib/mysql
  label: Var lib mysql
  default_host_subpath: db-var-lib-mysql
